INSERT INTO events VALUES (nextval('events_id_seq'),'Issyk-Kul,Cholpon-Ata','2022-09-29',
'Thousands of years ago, there occurred a division between the nomads and the farmers. The Kyrgyz became nomads that moved from one pasture to another with their herds, spending summers high in the mountains and winters in the lower valleys. This lifestyle is reflected in the everyday life and entertainment of the Kyrgyz people. Visitors can see these firsthand at various ethno festivals, but the best way to experience the full richness of the local culture and customs, you should visit the World Nomad Games.First held in 2014, and now held every two years, the World Nomad Games gathers athletes, artists, craftsmen, and visitors from around the world. In previous years, delegations from almost every continent (except Antarctica) have competed, including Kazakhstan, Uzbekistan, Mongolia, China, Russia, Turkey, and the United States. The sports and competitions feature different games that have existed for centuries, including races, horse games, hunting demonstrations, and wrestling.','http://worldnomadgames.com/en/','World Nomad Games');
INSERT INTO events VALUES (nextval('events_id_seq'),'Chuy,Bishkek','2023-03-21',
'Nooruz (or Nowruz) is celebrated on the spring equinox, usually March 21st, and marks the beginning of a new year. Although originally a pagan holiday, the equinox is considered a holy day among Zoroastrians, and is celebrated across Eurasia.Traditionally the day started off with music, especially with the karnay, a long horn similar to a trumpet. Tables are set with a white tablecloth and a spread of food, most prominent of which is sumolok. Sumolok is made from wheatgrass that has been cooked, sometimes alone, sometimes with flour and oil, for hours or even days. Small stones are added to the large cooking pot to keep the grains from burning, and legend has it that if you find a stone in your cup, you can make a wish and it’ll come true. Since sumolok takes so long to cook, women usually gather to sing to pass the time and to make sure that the dish is infused with positive energy.','http://worldnomadgames.com/en/','Nooruz');

INSERT INTO event_image_urls VALUES (1,'https://i.ibb.co/Hn4Jqzs/events15.jpg');
INSERT INTO event_image_urls VALUES (1,'https://i.ibb.co/J2t5x8w/events12.jpg');
INSERT INTO event_image_urls VALUES (1,'https://i.ibb.co/LQSrhc5/events13.jpg');
INSERT INTO event_image_urls VALUES (1,'https://i.ibb.co/Czw59kh/events11.jpg');
INSERT INTO event_image_urls VALUES (2,'https://i.ibb.co/GPpKPxp/events14.jpg');
INSERT INTO event_image_urls VALUES (2,'https://i.ibb.co/k22VZcy/events21.jpg');
INSERT INTO event_image_urls VALUES (2,'https://i.ibb.co/7Chqwmb/events2.jpg');
INSERT INTO event_image_urls VALUES (2,'https://i.ibb.co/8N8GKb4/events22.jpg');