CREATE TABLE articles (id bigserial NOT NULL, body VARCHAR(10000) NOT NULL, image_url VARCHAR(255) NOT NULL, title VARCHAR(500) NOT NULL, user_id int8, PRIMARY KEY (id));
CREATE TABLE blog_comments (blog_id int8 NOT NULL, comment_id int8 NOT NULL, PRIMARY KEY (blog_id, comment_id));
CREATE TABLE blog_likes (blog_id int8 NOT NULL, user_id int8 NOT NULL, PRIMARY KEY (blog_id, user_id));
CREATE TABLE blogs (id  bigserial NOT NULL, body VARCHAR(10000) NOT NULL, status VARCHAR(255), title VARCHAR(500) NOT NULL, author_id int8, PRIMARY KEY (id));
CREATE TABLE comment_likes (comment_id int8 NOT NULL, liked_users_id int8 NOT NULL, PRIMARY KEY (comment_id, liked_users_id));
CREATE TABLE comments (id  bigserial NOT NULL, body VARCHAR(2000) NOT NULL, creation_date DATE, user_id int8 NOT NULL, PRIMARY KEY (id));
CREATE TABLE favorite_places (user_id int8 NOT NULL, place_id int8 NOT NULL, PRIMARY KEY (user_id, place_id));
CREATE TABLE place_comments (place_id int8 NOT NULL, comment_id int8 NOT NULL, PRIMARY KEY (place_id, comment_id));
CREATE TABLE place_ratings (id  bigserial NOT NULL, rating int4 NOT NULL, place_id int8, user_id int8, PRIMARY KEY (id));
CREATE TABLE places (id  bigserial NOT NULL, address VARCHAR(255), description VARCHAR(2000) NOT NULL, image_url VARCHAR(255) NOT NULL, link_url VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, place_type VARCHAR(255), region VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE role (id  bigserial NOT NULL, role VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE user_role (user_id int8 NOT NULL, role_id int8 NOT NULL);
CREATE TABLE users (id  bigserial NOT NULL, email VARCHAR(255) NOT NULL, first_name VARCHAR(255), last_name VARCHAR(255), login VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, phone_number VARCHAR(255) NOT NULL, PRIMARY KEY (id));
ALTER TABLE blog_comments ADD CONSTRAINT UK_ny0y7e9s53y6l4sfgpksye42j UNIQUE (comment_id);
ALTER TABLE place_comments ADD CONSTRAINT UK_ja9pdfmnuagk0g89e29gpbw4n UNIQUE (comment_id);
ALTER TABLE articles ADD CONSTRAINT FKlc3sm3utetrj1sx4v9ahwopnr FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE blog_comments ADD CONSTRAINT FK155d2e10b59q2a6nbcvg9ihi4 FOREIGN KEY (comment_id) REFERENCES comments;
ALTER TABLE blog_comments ADD CONSTRAINT FKnadbu7mnnulxvib0jc5dqn7to FOREIGN KEY (blog_id) REFERENCES blogs;
ALTER TABLE blog_likes ADD CONSTRAINT FKfqaey79qg6v969ymdp40ft3b FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE blog_likes ADD CONSTRAINT FKojo8uaqhkmbtqa8duxtbq56w3 FOREIGN KEY (blog_id) REFERENCES blogs;
ALTER TABLE blogs ADD CONSTRAINT FKt8g0udj2fq40771g38t2t011n FOREIGN KEY (author_id) REFERENCES users;
ALTER TABLE comment_likes ADD CONSTRAINT FKjhjsx3g4rmc9ye8k5xafeprrk FOREIGN KEY (liked_users_id) REFERENCES users;
ALTER TABLE comment_likes ADD CONSTRAINT FK3wa5u7bs1p1o9hmavtgdgk1go FOREIGN KEY (comment_id) REFERENCES comments;
ALTER TABLE comments ADD CONSTRAINT FK8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE favorite_places ADD CONSTRAINT FK4pf98npou01hnsgywly8isn0u FOREIGN KEY (place_id) REFERENCES places;
ALTER TABLE favorite_places ADD CONSTRAINT FK5tmdgtn9286q309p0x4hv0cwc FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE place_comments ADD CONSTRAINT FKg9cjbcwnns5kmqxakxod2dwxp FOREIGN KEY (comment_id) REFERENCES comments;
ALTER TABLE place_comments ADD CONSTRAINT FK9gtx2cxplxjc9ef3l63ho39n4 FOREIGN KEY (place_id) REFERENCES places;
ALTER TABLE place_ratings ADD CONSTRAINT FKkfg5s7jd8h47f6s14g3xysurp FOREIGN KEY (place_id) REFERENCES places;
ALTER TABLE place_ratings ADD CONSTRAINT FKhu9y3jlohhtigrluc8c4gwgwd FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE user_role ADD CONSTRAINT FKa68196081fvovjhkek5m97n3y FOREIGN KEY (role_id) REFERENCES role;
ALTER TABLE user_role ADD CONSTRAINT FKj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES users;