INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'), 'Smile', 'Gorkiy street 1', 'ENTERTAINMENT', 'BISHKEK', 'https://i.ytimg.com/vi/BHh72G35VKs/maxresdefault.jpg', 'https://www.instagram.com/smile.kg/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Issyk-Kul', 'Not Specified', 'LAKE', 'ISSYK_KUL', 'https://thumbs.dreamstime.com/b/issyk-kul-lake-panorama-view-to-ruh-ordo-cultural-complex-near-mountains-background-cholpon-ata-kyrgyzstan-43482185.jpg', 'https://www.remotelands.com/destination/issyk-kul-lake', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Osh Bazaar', 'Chuy 202', 'BAZAAR', 'BISHKEK', 'https://planetofhotels.com/guide/sites/default/files/styles/paragraph__hero_banner__hb_image__1880bp/public/hero_banner/Osh-Bazaar.jpg', 'https://kyrgyzstan-tourism.com/blog/osh-bazar-place-to-visit-in-bishkek/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Ala Archa National Park', 'Not specified', 'PARK', 'CHUY', 'https://i0.wp.com/nomads-yurt.com/wp-content/uploads/2019/03/Ala-Archa-2.jpg?fit=1211%2C807&ssl=1', 'https://alaarchapark.kg/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Burana', 'Not Specified', 'HISTORICAL_BUILDING', 'CHUY', 'https://bulak.kg/wp-content/uploads/2022/06/1572173131_bashnja-burana-kyrgyzstan-3.jpg', 'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%88%D0%BD%D1%8F_%D0%91%D1%83%D1%80%D0%B0%D0%BD%D0%B0', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Son Kul', 'Not Specified', 'LAKE', 'NARYN', 'https://www.snowleopardtours.com/wp-content/uploads/2012/04/Song-Kul-Lake-scaled.jpg', 'https://central-asia.guide/kyrgyzstan/destinations-kg/naryn/son-kul/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Arslanbob', 'Not Speciifed', 'FOREST', 'JALAL_ABAD', 'https://too.kg/wp-content/uploads/c_vlad_ushakov_12-1024x553.jpg', 'https://central-asia.guide/kyrgyzstan/destinations-kg/jalalabad/arslanbob/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Yntymak Park', 'Not Specified', 'PARK', 'BISHKEK', 'https://24.kg/files/media/225/225431.jpg', 'https://2gis.kg/bishkek/geo/70030076191109369', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Dordoi Plaza', 'Ibraimova 115', 'MALL', 'BISHKEK', 'https://avatars.mds.yandex.net/get-altay/5449402/2a0000017f97602713c996a45cd657c7bc5d/XXL', 'https://dordoiplaza.kg/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Navat', 'Baytik Baatyr 55', 'TEAHOUSE', 'BISHKEK', 'https://www.restoclub.ru/uploads/place_thumbnail_big/3/a/d/d/3add849f3c0e1c3a8d2dcd42e1c9de97.jpg', 'https://www.navat.kg/dostavka/?utm_source=google&utm_medium=cpc&utm_campaign=dostavka', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Opera and Ballet theatre', 'Sovetskiy 167', 'THEATRE', 'BISHKEK', 'https://manas.news/wp-content/uploads/2021/03/01032021-6.jpg', 'https://ticket.kg/zavedenie/teatr_opery_i_baleta', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Ala Too Square', 'Chuy', 'SQUARE', 'BISHKEK', 'https://www.baibol.kg/img/attraction_gallery/152413810420654.jpg', 'https://www.baibol.kg/ru/tourism-in-kyrgyzstan/attractions/ala-too-square', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Sary-Chelek', 'Not Specified', 'LAKE', 'JALAL_ABAD', 'https://sputnik.kg/img/104502/71/1045027144_421:0:1269:933_1920x0_80_0_0_f9991cf73d71089f415ab5ee405907c8.jpg', 'https://kyrgyzstan-tourism.com/sights/sary-chelek/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Jeti-Oguz', 'Not Specified', 'GORGE', 'ISSYK_KUL', 'https://triptokyrgyzstan.com/sites/default/files/media/image/c_genadii_vyenko_1_0.jpg', 'https://thesandyfeet.com/things-to-do-in-jeti-oguz-kyrgyzstan/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Novotel', 'Manas avenue', 'HOTEL', 'BISHKEK', 'https://www.ahstatic.com/photos/a145_ho_00_p_1024x768.jpg', 'https://www.tripadvisor.ru/Hotel_Review-g293948-d23274172-Reviews-Novotel_Bishkek_City_Center-Bishkek.html', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Sheraton', 'Kiev 148', 'HOTEL', 'BISHKEK', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/08/3c/d6/sheraton-bishkek.jpg?w=700&h=-1&s=1', 'https://www.marriott.com.ru/hotels/travel/frusi-sheraton-bishkek/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Cinematica', 'Ibraimova 115', 'CINEMA', 'BISHKEK', 'https://kloop.kg/wp-content/uploads/2022/03/IMAX.jpg', 'https://kg.kinoafisha.info/bishkek/cinema/8327039/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Kegeti', 'Not Specified', 'GORGE', 'BISHKEK', 'https://upload.tury.club/data/839a7f2c2d7cf82d3a6570515f6a13a3/NDwNDtsv/hfVx4kR1.jpg', 'https://too.kg/kegety/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Bellagio Coffee', 'Kiev 71', 'CAFE', 'BISHKEK', 'https://lh3.googleusercontent.com/p/AF1QipOHKq6Ss5LHRhOsA10f2HQnr4NFjeXwOurzh-px=w768-h768-n-o-v1', 'https://www.instagram.com/bellagio_coffee/?hl=ru', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, region, image_url, link_url, description) VALUES (nextval('places_id_seq'),'Chunkurchak', 'Not Specified', 'SKY_RESORT', 'CHUY', 'https://www.chunkurchak.kg/images/lift3.jpg', 'https://www.chunkurchak.kg/', 'Great place for spending time');
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted)
VALUES (nextval('users_id_seq'), '$2a$12$R1zew/xsTUq4eWAiZCsrG.c1ouk8SvN.eJveY3RkoFh1PI1BtvGU.', 'admin', 'admin', 'admin@admin.a', '+000000000000', true, false);
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted)
VALUES (nextval('users_id_seq'), '$2a$12$tzp.n0FfFjWMoh6ojeiQPOQDSw.IUdGUJGxVJ0f8uNeSMWUux2X3K', 'Asel', 'Asel', 'Asel@admin.a', '+1542134213213', true, false);
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted)
VALUES (nextval('users_id_seq'), '$2a$12$tzp.n0FfFjWMoh6ojeiQPOQDSw.IUdGUJGxVJ0f8uNeSMWUux2X3K', 'Adelina', 'Adelina', 'Adelina@admin.a', '+42424124213321', true, false);
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted)
VALUES (nextval('users_id_seq'), '$2a$12$tzp.n0FfFjWMoh6ojeiQPOQDSw.IUdGUJGxVJ0f8uNeSMWUux2X3K', 'Kanay', 'Kanay', 'Kanay@admin.a', '+42142142142133', true, false);
INSERT INTO roles (user_id, roles) VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles (user_id, roles) VALUES (2, 'ROLE_ADMIN');
INSERT INTO roles (user_id, roles) VALUES (3, 'ROLE_ADMIN');
INSERT INTO roles (user_id, roles) VALUES (4, 'ROLE_ADMIN');
