INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'), 'Smile', 'Gorkiy street 1', 'SPORT_CENTER','ENTERTAINMENT', 'BISHKEK', 'https://www.instagram.com/smile.kg/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Osh Bazaar', 'Chuy 202', 'BAZAAR','SEE_AND_TRY', 'BISHKEK', 'https://kyrgyzstan-tourism.com/blog/osh-bazar-place-to-visit-in-bishkek/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Issyk-Kul', 'Not Specified', 'LAKE','SEE_AND_TRY', 'ISSYK_KUL', 'https://www.remotelands.com/destination/issyk-kul-lake', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Ala Archa National Park', 'Not specified', 'PARK','SEE_AND_TRY', 'CHUY', 'https://alaarchapark.kg/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Burana', 'Not Specified', 'HISTORICAL_BUILDING','SEE_AND_TRY', 'CHUY', 'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%88%D0%BD%D1%8F_%D0%91%D1%83%D1%80%D0%B0%D0%BD%D0%B0', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Son Kul', 'Not Specified', 'LAKE','SEE_AND_TRY', 'NARYN', 'https://central-asia.guide/kyrgyzstan/destinations-kg/naryn/son-kul/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Arslanbob', 'Not Speciifed', 'FOREST','SEE_AND_TRY', 'JALAL_ABAD', 'https://central-asia.guide/kyrgyzstan/destinations-kg/jalalabad/arslanbob/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Yntymak Park', 'Not Specified', 'PARK','SEE_AND_TRY', 'BISHKEK', 'https://2gis.kg/bishkek/geo/70030076191109369', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Dordoi Plaza', 'Ibraimova 115', 'MALL','ENTERTAINMENT', 'BISHKEK', 'https://dordoiplaza.kg/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Navat', 'Baytik Baatyr 55', 'TEA_HOUSE','EAT', 'BISHKEK','https://www.navat.kg/dostavka/?utm_source=google&utm_medium=cpc&utm_campaign=dostavka', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Opera and Ballet theatre', 'Sovetskiy 167', 'THEATRE','ENTERTAINMENT', 'BISHKEK','https://ticket.kg/zavedenie/teatr_opery_i_baleta', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Ala Too Square', 'Chuy', 'SQUARE','SEE_AND_TRY', 'BISHKEK', 'https://www.baibol.kg/ru/tourism-in-kyrgyzstan/attractions/ala-too-square', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Sary-Chelek', 'Not Specified', 'LAKE','SEE_AND_TRY', 'JALAL_ABAD','https://kyrgyzstan-tourism.com/sights/sary-chelek/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Jeti-Oguz', 'Not Specified', 'GORGE','SEE_AND_TRY', 'ISSYK_KUL','https://thesandyfeet.com/things-to-do-in-jeti-oguz-kyrgyzstan/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Novotel', 'Manas avenue', 'HOTEL','STAY', 'BISHKEK','https://www.tripadvisor.ru/Hotel_Review-g293948-d23274172-Reviews-Novotel_Bishkek_City_Center-Bishkek.html', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Sheraton', 'Kiev 148', 'HOTEL','STAY', 'BISHKEK', 'https://www.marriott.com.ru/hotels/travel/frusi-sheraton-bishkek/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Cinematica', 'Ibraimova 115', 'CINEMA','ENTERTAINMENT', 'BISHKEK','https://kg.kinoafisha.info/bishkek/cinema/8327039/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Kegeti', 'Not Specified', 'GORGE','SEE_AND_TRY', 'BISHKEK','https://too.kg/kegety/', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Bellagio Coffee', 'Kiev 71', 'CAFE','EAT', 'BISHKEK','https://www.instagram.com/bellagio_coffee/?hl=ru', 'Great place for spending time');
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description) VALUES (nextval('places_id_seq'),'Chunkurchak', 'Not Specified', 'SKY_RESORT','ENTERTAINMENT', 'CHUY','https://www.chunkurchak.kg/', 'Great place for spending time');
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted,image_url)
VALUES (nextval('users_id_seq'), '$2a$12$v32h8OfSAeWV9KX.FnJ/kuaedWsaptVUyDDJE52rAaRXnwhcmgTwS', 'admin', 'admin', 'admin@admin.a', '+000000000000', true, false,'https://www.pngitem.com/pimgs/m/247-2472306_admin-anonymous-person-icon-hd-png-download.png');
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted,image_url)
VALUES (nextval('users_id_seq'), '$2a$12$tzp.n0FfFjWMoh6ojeiQPOQDSw.IUdGUJGxVJ0f8uNeSMWUux2X3K', 'Asel', 'Asel', 'Asel@admin.a', '+1542134213213', true, false,'https://www.pngitem.com/pimgs/m/247-2472306_admin-anonymous-person-icon-hd-png-download.png');
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted,image_url)
VALUES (nextval('users_id_seq'), '$2a$12$tzp.n0FfFjWMoh6ojeiQPOQDSw.IUdGUJGxVJ0f8uNeSMWUux2X3K', 'Adelina', 'Adelina', 'Adelina@admin.a', '+42424124213321', true, false,'https://www.pngitem.com/pimgs/m/247-2472306_admin-anonymous-person-icon-hd-png-download.png');
INSERT INTO users (id, password, first_name, last_name, email, phone_number, is_activated, is_deleted,image_url)
VALUES (nextval('users_id_seq'), '$2a$12$tzp.n0FfFjWMoh6ojeiQPOQDSw.IUdGUJGxVJ0f8uNeSMWUux2X3K', 'Kanay', 'Kanay', 'Kanay@admin.a', '+42142142142133', true, false,'https://www.pngitem.com/pimgs/m/247-2472306_admin-anonymous-person-icon-hd-png-download.png');
INSERT INTO roles (user_id, roles) VALUES (1, 'ROLE_SUPERADMIN');
INSERT INTO roles (user_id, roles) VALUES (2, 'ROLE_ADMIN');
INSERT INTO roles (user_id, roles) VALUES (3, 'ROLE_ADMIN');
INSERT INTO roles (user_id, roles) VALUES (4, 'ROLE_ADMIN');
INSERT INTO place_image_urls VALUES (1,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (2,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (3,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (4,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (5,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (6,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (7,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (8,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (9,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (10,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (11,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (12,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (13,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (14,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (15,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (16,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (17,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (18,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (19,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
INSERT INTO place_image_urls VALUES (20,'https://bigseventravel.com/wp-content/uploads/2021/07/Kyrgyzstan-1.jpg');
