INSERT INTO articles (id, title, body,user_id) VALUES (nextval('articles_id_seq'), '5 reasons to visit Kyrgyzstan',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In commodo ipsum sit amet augue sagittis mollis. Aenean consequat augue interdum felis commodo, vitae fermentum nisi suscipit. Ut tristique lacus ac imperdiet blandit. Suspendisse non massa auctor, placerat ligula sed, consectetur purus. Integer vel ex libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque facilisis nisi ut justo rhoncus, eu hendrerit urna ornare.

Ut rhoncus ultricies ligula, id pulvinar erat. Pellentesque ultricies porttitor nulla sit amet facilisis. Donec in erat sed lacus eleifend auctor at ac odio. Morbi quis venenatis urna. Integer sit amet euismod purus. Mauris cursus urna velit, non venenatis leo pretium ut. Quisque massa felis, consequat id imperdiet quis, feugiat eu arcu. Sed lobortis vitae augue vel cursus. Suspendisse pulvinar ac urna elementum faucibus. Sed erat nisl, hendrerit quis congue at, mollis vel libero. Fusce ultrices ante non varius mattis. Fusce eu neque eu quam viverra blandit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas et eros tellus. Fusce arcu sem, commodo euismod turpis ac, fermentum fringilla ligula.

Donec rhoncus ac erat ac accumsan. Suspendisse quis lacus tortor. Donec finibus ultrices auctor. Suspendisse fermentum ligula quis nisl posuere maximus. Donec eget felis ac dui tristique ullamcorper eget eget ipsum. Suspendisse porta varius turpis, eget maximus mauris pharetra sit amet. Suspendisse sit amet risus augue. Cras finibus lacus eu ipsum volutpat blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus vitae suscipit elit, id aliquet quam. Morbi congue elementum pellentesque. Suspendisse nisl mauris, rutrum quis risus sed, porta varius nibh. Morbi molestie, libero ut dictum sollicitudin, elit ante dapibus erat, nec egestas nibh nibh vel lorem. Phasellus sodales metus vitae tempor porttitor. Suspendisse ut ipsum non nunc fermentum tristique.

Vivamus sed lectus eget dui elementum luctus posuere quis nisi. Pellentesque vitae consectetur dui. Fusce eleifend nisi id interdum laoreet. Etiam pulvinar consequat ex at posuere. Quisque venenatis libero nibh, a sollicitudin elit varius in. Fusce non pellentesque dolor. Curabitur feugiat metus vitae consectetur tempor. Aenean aliquet ante aliquet venenatis imperdiet. Vestibulum condimentum lectus metus, vitae finibus nulla aliquam non. Aliquam ac dui dui. Sed finibus ullamcorper sagittis. Morbi quis interdum risus. Quisque quis iaculis dui. Aenean vehicula sagittis nunc, nec ultricies eros luctus ut. Sed ac volutpat enim, id dapibus lorem. Nam interdum ipsum ipsum, et condimentum lacus eleifend ac.

Ut posuere, mauris vitae luctus hendrerit, nisl odio suscipit dui, non convallis purus nunc fermentum eros. Quisque tincidunt velit vel tellus consectetur, et iaculis mauris aliquam. Mauris pulvinar ac tortor vitae lobortis. Mauris vel leo fringilla, posuere justo sit amet, tincidunt metus. Morbi eu elit eleifend ante aliquam tempus. Fusce et lectus tincidunt, molestie risus sed, sollicitudin ex. Mauris gravida ornare nunc id blandit. Nunc placerat, augue ac fringilla luctus, eros lectus posuere enim, at commodo dui ex a velit. Ut elementum aliquet sapien. Aliquam ex felis, ullamcorper ut dui eget, ullamcorper dignissim elit.',
        1);
INSERT INTO articles (id, title, body,user_id) VALUES (nextval('articles_id_seq'), 'Issyk-Kul Lake - All You Need To Know',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In commodo ipsum sit amet augue sagittis mollis. Aenean consequat augue interdum felis commodo, vitae fermentum nisi suscipit. Ut tristique lacus ac imperdiet blandit. Suspendisse non massa auctor, placerat ligula sed, consectetur purus. Integer vel ex libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque facilisis nisi ut justo rhoncus, eu hendrerit urna ornare.

Ut rhoncus ultricies ligula, id pulvinar erat. Pellentesque ultricies porttitor nulla sit amet facilisis. Donec in erat sed lacus eleifend auctor at ac odio. Morbi quis venenatis urna. Integer sit amet euismod purus. Mauris cursus urna velit, non venenatis leo pretium ut. Quisque massa felis, consequat id imperdiet quis, feugiat eu arcu. Sed lobortis vitae augue vel cursus. Suspendisse pulvinar ac urna elementum faucibus. Sed erat nisl, hendrerit quis congue at, mollis vel libero. Fusce ultrices ante non varius mattis. Fusce eu neque eu quam viverra blandit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas et eros tellus. Fusce arcu sem, commodo euismod turpis ac, fermentum fringilla ligula.

Donec rhoncus ac erat ac accumsan. Suspendisse quis lacus tortor. Donec finibus ultrices auctor. Suspendisse fermentum ligula quis nisl posuere maximus. Donec eget felis ac dui tristique ullamcorper eget eget ipsum. Suspendisse porta varius turpis, eget maximus mauris pharetra sit amet. Suspendisse sit amet risus augue. Cras finibus lacus eu ipsum volutpat blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus vitae suscipit elit, id aliquet quam. Morbi congue elementum pellentesque. Suspendisse nisl mauris, rutrum quis risus sed, porta varius nibh. Morbi molestie, libero ut dictum sollicitudin, elit ante dapibus erat, nec egestas nibh nibh vel lorem. Phasellus sodales metus vitae tempor porttitor. Suspendisse ut ipsum non nunc fermentum tristique.

Vivamus sed lectus eget dui elementum luctus posuere quis nisi. Pellentesque vitae consectetur dui. Fusce eleifend nisi id interdum laoreet. Etiam pulvinar consequat ex at posuere. Quisque venenatis libero nibh, a sollicitudin elit varius in. Fusce non pellentesque dolor. Curabitur feugiat metus vitae consectetur tempor. Aenean aliquet ante aliquet venenatis imperdiet. Vestibulum condimentum lectus metus, vitae finibus nulla aliquam non. Aliquam ac dui dui. Sed finibus ullamcorper sagittis. Morbi quis interdum risus. Quisque quis iaculis dui. Aenean vehicula sagittis nunc, nec ultricies eros luctus ut. Sed ac volutpat enim, id dapibus lorem. Nam interdum ipsum ipsum, et condimentum lacus eleifend ac.

Ut posuere, mauris vitae luctus hendrerit, nisl odio suscipit dui, non convallis purus nunc fermentum eros. Quisque tincidunt velit vel tellus consectetur, et iaculis mauris aliquam. Mauris pulvinar ac tortor vitae lobortis. Mauris vel leo fringilla, posuere justo sit amet, tincidunt metus. Morbi eu elit eleifend ante aliquam tempus. Fusce et lectus tincidunt, molestie risus sed, sollicitudin ex. Mauris gravida ornare nunc id blandit. Nunc placerat, augue ac fringilla luctus, eros lectus posuere enim, at commodo dui ex a velit. Ut elementum aliquet sapien. Aliquam ex felis, ullamcorper ut dui eget, ullamcorper dignissim elit.',
        1);
INSERT INTO articles (id, title, body,user_id) VALUES (nextval('articles_id_seq'), 'Топ 10 лучших мест в БИШКЕКЕ!',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In commodo ipsum sit amet augue sagittis mollis. Aenean consequat augue interdum felis commodo, vitae fermentum nisi suscipit. Ut tristique lacus ac imperdiet blandit. Suspendisse non massa auctor, placerat ligula sed, consectetur purus. Integer vel ex libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque facilisis nisi ut justo rhoncus, eu hendrerit urna ornare.

Ut rhoncus ultricies ligula, id pulvinar erat. Pellentesque ultricies porttitor nulla sit amet facilisis. Donec in erat sed lacus eleifend auctor at ac odio. Morbi quis venenatis urna. Integer sit amet euismod purus. Mauris cursus urna velit, non venenatis leo pretium ut. Quisque massa felis, consequat id imperdiet quis, feugiat eu arcu. Sed lobortis vitae augue vel cursus. Suspendisse pulvinar ac urna elementum faucibus. Sed erat nisl, hendrerit quis congue at, mollis vel libero. Fusce ultrices ante non varius mattis. Fusce eu neque eu quam viverra blandit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas et eros tellus. Fusce arcu sem, commodo euismod turpis ac, fermentum fringilla ligula.

Donec rhoncus ac erat ac accumsan. Suspendisse quis lacus tortor. Donec finibus ultrices auctor. Suspendisse fermentum ligula quis nisl posuere maximus. Donec eget felis ac dui tristique ullamcorper eget eget ipsum. Suspendisse porta varius turpis, eget maximus mauris pharetra sit amet. Suspendisse sit amet risus augue. Cras finibus lacus eu ipsum volutpat blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus vitae suscipit elit, id aliquet quam. Morbi congue elementum pellentesque. Suspendisse nisl mauris, rutrum quis risus sed, porta varius nibh. Morbi molestie, libero ut dictum sollicitudin, elit ante dapibus erat, nec egestas nibh nibh vel lorem. Phasellus sodales metus vitae tempor porttitor. Suspendisse ut ipsum non nunc fermentum tristique.

Vivamus sed lectus eget dui elementum luctus posuere quis nisi. Pellentesque vitae consectetur dui. Fusce eleifend nisi id interdum laoreet. Etiam pulvinar consequat ex at posuere. Quisque venenatis libero nibh, a sollicitudin elit varius in. Fusce non pellentesque dolor. Curabitur feugiat metus vitae consectetur tempor. Aenean aliquet ante aliquet venenatis imperdiet. Vestibulum condimentum lectus metus, vitae finibus nulla aliquam non. Aliquam ac dui dui. Sed finibus ullamcorper sagittis. Morbi quis interdum risus. Quisque quis iaculis dui. Aenean vehicula sagittis nunc, nec ultricies eros luctus ut. Sed ac volutpat enim, id dapibus lorem. Nam interdum ipsum ipsum, et condimentum lacus eleifend ac.

Ut posuere, mauris vitae luctus hendrerit, nisl odio suscipit dui, non convallis purus nunc fermentum eros. Quisque tincidunt velit vel tellus consectetur, et iaculis mauris aliquam. Mauris pulvinar ac tortor vitae lobortis. Mauris vel leo fringilla, posuere justo sit amet, tincidunt metus. Morbi eu elit eleifend ante aliquam tempus. Fusce et lectus tincidunt, molestie risus sed, sollicitudin ex. Mauris gravida ornare nunc id blandit. Nunc placerat, augue ac fringilla luctus, eros lectus posuere enim, at commodo dui ex a velit. Ut elementum aliquet sapien. Aliquam ex felis, ullamcorper ut dui eget, ullamcorper dignissim elit.',
        1);
INSERT INTO article_image_urls VALUES (1,'https://oir.mobi/uploads/posts/2021-05/thumbs/1622302143_13-oir_mobi-p-priroda-kirgizstana-priroda-krasivo-foto-13.jpg');
INSERT INTO article_image_urls VALUES (2,'https://concept.kg/media/redactor/ik_DE2wlxk.jpg');
INSERT INTO article_image_urls VALUES (3,'https://tripplanet.ru/wp-content/uploads/asia/kyrgyzstan/bishkek/dostoprimechatelnosti-bishkeka.jpg');

