INSERT INTO articles (id, title, body, image_url, user_id) VALUES (nextval('articles_id_seq'), '5 reasons to visit Kyrgyzstan',
'Kyrgyzstan is a mountainous oasis in the desert steppes of Central Asia, enclosed by the celestial Tien-Shan Mountain ranges, with countless glaciers and lakes, from where water flows abundantly. It is not surprising that the country is popular amongst hikers. Many people call Kyrgyzstan as a “Second Switzerland” because of its wonderful and breathtaking scenery. не законченый так как с базой данных возникли проблемы', 'https://www.journalofnomads.com/wp-content/uploads/2021/03/Horse-riding-in-Kyrgyzstan.jpg', 1);
INSERT INTO articles (id, title, body, image_url, user_id) VALUES (nextval('articles_id_seq'), 'Статья на русском',
'Иску́сство (от церк.-слав. искусьство, ст.‑слав. искоусъ — искушение, опыт, испытание) — одна из наиболее общих категорий эстетики, искусствознания и художественной практики. Обычно под искусством подразумевают образное осмысление действительности; процесс и итог выражения внутреннего и внешнего (по отношению к творцу) мира. Следовательно, искусство — творческая деятельность, отражающая интересы не только самого автора, но и других людей. «Общеинтересное в жизни, — писал Николай Чернышевский, — вот содержание искусства». Совсем иначе определял сущность «волшебства, называемого искусством» Владимир Набоков: «В гамме мировых мер есть такая точка, где переходят одно в другое воображение и знание, точка, которая достигается уменьшением крупных вещей и увеличением малых: точка искусства». Впрочем, в подобных определениях смешиваются понятия различного объёма и содержательного уровня: искусство, художество, отражение, образное мышление, творчество.', 'https://arthive.net/res/media/img/oy800/ref/941/339540@2x.jpg', 1);
INSERT INTO articles (id, title, body, image_url, user_id) VALUES (nextval('articles_id_seq'), 'Топ 10 лучших мест в БИШКЕКЕ!',
'Привет, Асель! Привет, Канай байке! Привет Аделина! Стресс – состояние психологического и физического напряжения в ответ на внешнее воздействие. Его способны вызвать затруднительные ситуации, монотонная деятельность и эмоциональные факторы. Стресс помогает адаптироваться к изменчивой окружающей среде, но может стать причиной отрицательных для здоровья последствий.', 'https://wallpapercave.com/wp/wp7856136.jpg', 1);

INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status) VALUES (false, nextval('blogs_id_seq'), 1, 'How to be a millionaire',
'It turns out that most millionaires share similar habits and principles. And that means you can start building those same habits and following those same principles starting today so you can become a millionaire yourself someday! dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', 'APPROVED');
INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status) VALUES (false, nextval('blogs_id_seq'), 1, 'How to be a millionaire',
'It t2133st millionaires share similar habits and principles. And that means you can start building those same habits and following those same principles starting today so you can become a millionaire yourself someday! dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', 'REJECTED');
INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status) VALUES (false, nextval('blogs_id_seq'), 1, 'How to be a millionaire',
'123
123
123
123
123
123', 'PENDING');