INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Shar', 'Naryn,Bash-Kaiyndy', 'WATERFALL','SIGHTSEEING', 'NARYN','https://asiamountains.net/adventure/horseback-riding-tours/horseback-riding-tour-from-naryn-to-tash-rabat/', 'description',41.06123258966782,76.01064524012813);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Belogorka', 'Chuy,Tash-Bulak', 'WATERFALL','SIGHTSEEING', 'CHUY','https://travelbar.kg/listings/459', 'description',42.511241879176964,74.29744019784836);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Golubinyi', 'Chuy,Chon-Kurchak', 'WATERFALL','SIGHTSEEING', 'CHUY','https://strannik.kg/excursion-to-chon-kurchak/', 'description',42.677350249008924,74.6014287723974);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Barskoon', 'Issyk-Kul,Barskoon', 'WATERFALL','SIGHTSEEING', 'ISSYK_KUL','https://travelbar.kg/listings/464', 'description',42.0101134283244,77.60762439783147);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Abshir-Ata', 'Osh,Kyzyl-Kiya', 'WATERFALL','SIGHTSEEING', 'OSH','https://too.kg/abshir-ata/', 'description',40.162595569402775,72.3627379977705);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Tash-Rabat', 'Naryn,At-Bashi', 'HISTORICAL_BUILDING','SIGHTSEEING', 'NARYN','https://tenti.kg/ru/tours/36/kel-suu-kl-suu', 'description',40.830770899846826,75.2985966455068);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'State Philharmonic', 'Chuy Avenue 253', 'HISTORICAL_BUILDING','SIGHTSEEING', 'BISHKEK','https://www.kassir.kg/hall/%D0%9A%D1%8B%D1%80%D0%B3%D1%8B%D0%B7%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BD%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%84%D0%B8%D0%BB%D0%B0%D1%80%D0%BC%D0%BE%D0%BD%D0%B8%D1%8F', 'description',42.87797896647584,74.5876236355818);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Burana', 'Chuy,Tokmok', 'HISTORICAL_BUILDING','SIGHTSEEING', 'CHUY','https://concept.kg/tours/inbounds/32/', 'description',42.73333211661545, 75.33316130475146);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Teskey Ala-Too', 'Issyk-Kul,Karakol', 'ALPINISM','SIGHTSEEING', 'ISSYK_KUL','https://www.baibol.kg/ru/tourism-in-kyrgyzstan/attractions/%D1%82eskey-%D0%B0la-too-ridge', 'description',42.00009484427672, 77.49999996572805);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Pobeda Peak', 'Issyk-Kul,Kakshaal', 'ALPINISM','SIGHTSEEING', 'ISSYK_KUL','https://www.centralasia-travel.com/ru/expeditions/pobeda', 'description',42.03627873443639, 80.12924753907441);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Lenin Peak', 'Osh,Chon-Alai', 'ALPINISM','SIGHTSEEING', 'OSH','https://www.centralasia-travel.com/ru/expeditions/lenin', 'description',39.344094678851256, 72.87759534405674);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Khan-Tengri', 'Issyk-Kul,Tengri-Tag', 'ALPINISM','SIGHTSEEING', 'ISSYK_KUL','https://www.centralasia-travel.com/ru/expeditions/khan-tengry', 'description',42.211116750700704, 80.17431309850288);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Alay', 'Osh,Alay', 'ALPINISM','SIGHTSEEING', 'OSH','https://www.centralasia-travel.com/ru/countries/kirgistan/sights/alay-valley', 'description',39.66998970158205, 71.99999770932577);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Son-Kol','Naryn,Moldo-Too','LAKE','SIGHTSEEING', 'NARYN','https://travelbar.kg/listings/429', 'description',41.83382297217287, 75.13102395694608);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Sary-Chelek','Osh,Chatkal','LAKE','SIGHTSEEING', 'OSH','https://ticket.kg/event/trehdnevniy-tur-v-sari-chelek', 'description',41.88824238248667, 71.96077580545035);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Issyk-Kol','Issyk-Kul,Tien Shan','LAKE','SIGHTSEEING', 'ISSYK_KUL','https://bestway.kg/issyk-kul', 'description',42.38640906951673, 77.28596580968028);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Chatyr-Kol','Naryn,At-Bashi','LAKE','SIGHTSEEING', 'NARYN','https://triptokyrgyzstan.com/ru/destinations/places/ozero-chatyr-kul', 'description',40.63878213410726, 75.31737875652597);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Skazka', 'Issyk-Kul,Tosor', 'CANYON','SIGHTSEEING', 'ISSYK_KUL','https://too.kg/skazka/', 'description',42.15650667920104, 77.35431349783636);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Konorchek', 'Chuy,Krasnyy Most', 'CANYON','SIGHTSEEING', 'CHUY','https://asiamountains.net/adventure/tours/konorchek-canyons/', 'description',42.59651887917175, 75.78179104017946);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Merzbacher', 'Issyk-Kul,Saryjaz', 'HIKING','SIGHTSEEING', 'ISSYK_KUL','http://www.mastertour.kg/tury-po-kyrgyzstanu/trekking/zagadochnoe-ozero-mercbakhera-9-dnejj.html', 'description',42.21116171382065, 79.84927649865227);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Son-Kol', 'Naryn,Moldo-Too', 'HIKING','SIGHTSEEING', 'NARYN','https://ticket.kg/event/dvuhdnevniy-tur-v-sonkol', 'description',41.83382297217287, 75.13102395694608);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Jyrgalan', 'Issyk-Kul,Ak-Suu', 'HIKING','SIGHTSEEING', 'ISSYK_KUL','https://jyrgalan.com/tours/trekking-tours/', 'description',42.604279072345754, 79.02737364860404);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Elcin Peak', 'Issyk-Kul,Karakol', 'HIKING','SIGHTSEEING', 'ISSYK_KUL','https://triptokyrgyzstan.com/ru/tours/voskhozhdenie-na-pik-b-elcina-5168m', 'description',42.153182379060326, 78.43666696581057);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Ala-Kul', 'Issyk-Kul,Ak-Suu', 'HIKING','SIGHTSEEING', 'ISSYK_KUL','https://tour.too.kg/itinerary/%D1%82%D1%83%D1%80-%D0%BD%D0%B0-%D0%BE%D0%B7%D0%B5%D1%80%D0%BE-%D0%B0%D0%BB%D0%B0-%D0%BA%D1%83%D0%BB%D1%8C/', 'description',42.317467434326545, 78.53551305055596);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Sulaiman-Too', 'Osh,Osh', 'HIKING','SIGHTSEEING', 'OSH','https://bestofosh.com/ru/tur-po-sulaiman-too/', 'description',40.53028951214266, 72.78506218219451);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Kegeti', 'Chuy,Tokmok', 'GORGE','SIGHTSEEING', 'CHUY','https://www.instagram.com/kegeti_tour.kg/', 'description',42.691097321453654, 75.1796690130174);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Karakol', 'Issyk-Kul,Karakol', 'GORGE','SIGHTSEEING', 'ISSYK_KUL','http://www.karakoltour.kg/index.php/ru/', 'description',42.30204680393483, 78.48512555477642);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Jeti-Oguz', 'Issyk-Kul,Kyzyl-Suu', 'GORGE','SIGHTSEEING', 'ISSYK_KUL','https://sozvezdie-tour.ru/cat/tury/kirgiziya/dzhety-oguz', 'description',42.423262433433585, 78.21063984355364);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Chunkurchak', 'Chuy,Chunkurchak', 'GORGE','SIGHTSEEING', 'CHUY','https://www.instagram.com/chunkurchak/', 'description',42.64217664621759, 74.6188250525896);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Altyn-Arashan', 'Issyk-Kul,Ak-Suu', 'GORGE','SIGHTSEEING', 'ISSYK_KUL','https://travelbar.kg/listings/479', 'description',42.373163874656306, 78.6116182053961);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Alamedin', 'Chuy,Alamedin', 'GORGE','SIGHTSEEING', 'CHUY','https://travelbar.kg/listings/458', 'description',42.55192537124768, 74.66193888141089);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Fergana', 'Osh,Fergana', 'VALLEY','SIGHTSEEING', 'OSH','https://ak-sai.com/shop/express_tours/3-4-day-tours/extension-to-osh-city/', 'description',40.39044671020174, 72.11361864735501);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Navat', 'Tokombaev Street 32/4', 'CAFE','EAT', 'BISHKEK','http://navat.kg/', 'description',42.828184303354845, 74.60371110670975);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Ants Coffee', 'Erkindik Avenue 35', 'COFFEE_HOUSE','EAT', 'BISHKEK','https://www.instagram.com/ants.bishkek/', 'description',42.87235693341139, 74.60699574069139);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'IWA Roof Bar', 'Kievskaya Street 148B', 'RESTAURANT','EAT', 'BISHKEK','https://iwa.kg/', 'description',42.87480460463924, 74.5907715978607);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Faiza', 'Zhibek Zholu Street 555', 'CAFE','EAT', 'BISHKEK','https://faiza.kg/', 'description',42.88449605419548, 74.58714046895058);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Sheraton', 'Kievskaya Street 148B', 'HOTEL','STAY', 'BISHKEK','https://www.marriott.com.ru/hotels/travel/frusi-sheraton-bishkek/', 'description', 42.87480460463924, 74.5907715978607);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Supara', 'Chuy,Tash-Dobo', 'HOTEL','STAY', 'BISHKEK','https://supara.kg/ru/', 'description', 42.629852934953966, 74.62202992668828);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Ramada by Wyndham', 'Isanov Street 37', 'HOTEL','STAY', 'BISHKEK','https://www.wyndhamhotels.com/ramada/bishkek-kyrgyzstan/ramada-by-wyndham-bishkek-centre/overview', 'description',42.871142283267446, 74.59141908066583);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Novotel', 'Manas Avenue 16', 'HOTEL','STAY', 'BISHKEK','https://all.accor.com/hotel/A145/index.ru.shtml', 'description',42.86944349530029, 74.58720182669639);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Jannat', 'Tokombaev Street 21/2', 'HOTEL','STAY', 'BISHKEK','https://jannat.kg/', 'description',42.8208479445571, 74.61703739069547);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Hyatt Regency', 'Soviet Street 191', 'HOTEL','STAY', 'BISHKEK','https://www.hyatt.com/ru-RU/brands/hyatt-regency?&src=bbm_sem_bbm_search_google_eame_brand_catchall_Hyatt_Regency_hyatt%20regency&mckv=s-dc_pcrid_638809466077_mtid_5297kx13790&gclid=CjwKCAiAs8acBhA1EiwAgRFdwyvQ1VEU2GIEiRkCS5JnlOCsdtx80MzdB-sEanKUGaB4rRnp_bwZoxoCUdQQAvD_BwE&gclsrc=aw.ds', 'description', 42.87956749631123, 74.6127881808501);


INSERT INTO place_image_urls VALUES (1,'https://i.ibb.co/02NPJGP/wf-shaar1.jpg');
INSERT INTO place_image_urls VALUES (1,'https://i.ibb.co/KqzcdRN/wf-shaar2.jpg');
INSERT INTO place_image_urls VALUES (2,'https://i.ibb.co/Lv9v9Cg/wf-belogorka2.jpg');
INSERT INTO place_image_urls VALUES (2,'https://i.ibb.co/ftXYcbL/wf-belogorka1.jpg');
INSERT INTO place_image_urls VALUES (3,'https://i.ibb.co/GJXr6jb/wf-golub1.jpg');
INSERT INTO place_image_urls VALUES (4,'https://i.ibb.co/LZKhK3y/wf-barskoon1.jpg');
INSERT INTO place_image_urls VALUES (4,'https://i.ibb.co/6WZb8yr/wf-barskoon2.webp');
INSERT INTO place_image_urls VALUES (5,'https://i.ibb.co/DkQ2PsS/wf-abshirata2.jpg');
INSERT INTO place_image_urls VALUES (5,'https://i.ibb.co/dGYfCws/wf-abshirata1.jpg');
INSERT INTO place_image_urls VALUES (6,'https://i.ibb.co/gJZfGbs/sight-tashrabat2.jpg');
INSERT INTO place_image_urls VALUES (7,'https://i.ibb.co/kXnjmXx/sight-filarmony2.jpg');
INSERT INTO place_image_urls VALUES (7,'https://i.ibb.co/nQqb6pW/sight-filarmony1.jpg');
INSERT INTO place_image_urls VALUES (8,'https://i.ibb.co/y8MQXLq/sight-burana1.png');
INSERT INTO place_image_urls VALUES (8,'https://i.ibb.co/FxsrKGW/sight-burana2.webp');
INSERT INTO place_image_urls VALUES (9,'https://i.ibb.co/wLKff5v/mount-teskey1.webp');
INSERT INTO place_image_urls VALUES (10,'https://i.ibb.co/1MzrqfC/mount-peak1.jpg');
INSERT INTO place_image_urls VALUES (10,'https://i.ibb.co/jzdNB9W/mount-peak2.jpg');
INSERT INTO place_image_urls VALUES (11,'https://i.ibb.co/KKy2vnD/mount-lenin1.jpg');
INSERT INTO place_image_urls VALUES (11,'https://i.ibb.co/9rhjjGQ/mount-lenin2.jpg');
INSERT INTO place_image_urls VALUES (12,'https://i.ibb.co/D9C43qm/mount-khantengri1.jpg');
INSERT INTO place_image_urls VALUES (12,'https://i.ibb.co/MBQLyH3/mount-khantengri2.png');
INSERT INTO place_image_urls VALUES (12,'https://i.ibb.co/gwy61kP/mount-khantengri3.jpg');
INSERT INTO place_image_urls VALUES (13,'https://i.ibb.co/8bWqtLJ/mount-alay1.jpg');
INSERT INTO place_image_urls VALUES (13,'https://i.ibb.co/3NJs6w9/mount-alay2.jpg');
INSERT INTO place_image_urls VALUES (14,'https://i.ibb.co/Smj618T/lake-sonkul4.jpg');
INSERT INTO place_image_urls VALUES (14,'https://i.ibb.co/qgRp4q4/lake-sonkul2.jpg');
INSERT INTO place_image_urls VALUES (15,'https://i.ibb.co/dJNZtRV/lake-sc1.jpg');
INSERT INTO place_image_urls VALUES (15,'https://i.ibb.co/KzMFNG7/lake-sc2.jpg');
INSERT INTO place_image_urls VALUES (15,'https://i.ibb.co/37PwHGH/lake-sc3.jpg');
INSERT INTO place_image_urls VALUES (16,'https://i.ibb.co/DbzNGyS/lake-ik1.jpg');
INSERT INTO place_image_urls VALUES (16,'https://i.ibb.co/k5CH2jf/lake-ik2.jpg');
INSERT INTO place_image_urls VALUES (16,'https://i.ibb.co/mSm4Z0Q/lake-ik3.jpg');
INSERT INTO place_image_urls VALUES (17,'https://i.ibb.co/mqmgL04/lake-ck1.jpg');
INSERT INTO place_image_urls VALUES (17,'https://i.ibb.co/sHfn0NC/lake-ck2.jpg');
INSERT INTO place_image_urls VALUES (17,'https://i.ibb.co/tBgm5th/lake-ck3.jpg');
INSERT INTO place_image_urls VALUES (18,'https://i.ibb.co/Ct8D8R6/kanyon-skazka1.jpg');
INSERT INTO place_image_urls VALUES (18,'https://i.ibb.co/Km7C9jZ/kanyon-skazka2.jpg');
INSERT INTO place_image_urls VALUES (19,'https://i.ibb.co/KFx5VMs/kanyon-konorchak1.jpg');
INSERT INTO place_image_urls VALUES (20,'https://i.ibb.co/gRVBwRs/hike-merzbacher1.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/6N4Zw2k/lake-sonkul3.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/D9cZGJY/lake-sonkul1.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/09nsDJf/hike-sonkul2.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/9w2XmvD/hike-sonkul1.jpg');
INSERT INTO place_image_urls VALUES (22,'https://i.ibb.co/6BsBBRv/hike-jyrgalan1.jpg');
INSERT INTO place_image_urls VALUES (22,'https://i.ibb.co/GTLcnSV/hike-jyrgalan2.jpg');
INSERT INTO place_image_urls VALUES (23,'https://i.ibb.co/xm97MKj/hike-elchin1.jpg');
INSERT INTO place_image_urls VALUES (23,'https://i.ibb.co/q9651mF/hike-elchin2.jpg');
INSERT INTO place_image_urls VALUES (24,'https://i.ibb.co/JyZcgtc/hike-alakul1.jpg');
INSERT INTO place_image_urls VALUES (24,'https://i.ibb.co/NWhGkgy/hike-alakul2.jpg');
INSERT INTO place_image_urls VALUES (24,'https://i.ibb.co/djy9ZbY/hike-alakul3.jpg');
INSERT INTO place_image_urls VALUES (25,'https://i.ibb.co/tMVGJYb/mount-sulainman2.jpg');
INSERT INTO place_image_urls VALUES (25,'https://i.ibb.co/9pgJWks/mount-sulainman3.png');
INSERT INTO place_image_urls VALUES (26,'https://i.ibb.co/4df5rK7/gorge-kegeti1.jpg');
INSERT INTO place_image_urls VALUES (26,'https://i.ibb.co/9TRXvT9/gorge-kegeti2.jpg');
INSERT INTO place_image_urls VALUES (27,'https://i.ibb.co/8gGZLWG/gorge-karakol1.jpg');
INSERT INTO place_image_urls VALUES (27,'https://i.ibb.co/wJhwymW/gorge-karakol2.jpg');
INSERT INTO place_image_urls VALUES (28,'https://i.ibb.co/Y3YbPZ7/gorge-jetioguz1.jpg');
INSERT INTO place_image_urls VALUES (28,'https://i.ibb.co/DRkHdxw/gorge-jetioguz2.jpg');
INSERT INTO place_image_urls VALUES (29,'https://i.ibb.co/DVkRXrN/gorge-chunkurchak1.jpg');
INSERT INTO place_image_urls VALUES (29,'https://i.ibb.co/h2Pzb1C/gorge-chunkrchak2.jpg');
INSERT INTO place_image_urls VALUES (30,'https://i.ibb.co/Kw1bdTf/gorge-altyn-arashan1.jpg');
INSERT INTO place_image_urls VALUES (30,'https://i.ibb.co/gvd1wgw/gorge-altyn-arashan2.jpg');
INSERT INTO place_image_urls VALUES (31,'https://i.ibb.co/cDtPj0X/gorge-alamedin1.png');
INSERT INTO place_image_urls VALUES (31,'https://i.ibb.co/Yddk1Dx/gorge-alamedin2.jpg');
INSERT INTO place_image_urls VALUES (32,'https://i.ibb.co/23Vqwc9/dolina-fergana1.jpg');
INSERT INTO place_image_urls VALUES (33,'https://i.ibb.co/dMZJrSP/eat-navat1.jpg');
INSERT INTO place_image_urls VALUES (33,'https://i.ibb.co/Kyqbbv4/eat-navat2.jpg');
INSERT INTO place_image_urls VALUES (34,'https://i.ibb.co/b2GprJQ/eat-ants1.jpg');
INSERT INTO place_image_urls VALUES (34,'https://i.ibb.co/74F0dWs/eat-ants2.jpg');
INSERT INTO place_image_urls VALUES (35,'https://i.ibb.co/N65Kd3b/eat-iwa1.webp');
INSERT INTO place_image_urls VALUES (35,'https://i.ibb.co/9chgXCt/eat-iwa2.jpg');
INSERT INTO place_image_urls VALUES (36,'https://i.ibb.co/vZdQkzc/eat-faiza1.jpg');
INSERT INTO place_image_urls VALUES (37,'https://i.ibb.co/dgXYcPk/stay-sheraton1.webp');
INSERT INTO place_image_urls VALUES (37,'https://i.ibb.co/PjddtG7/stay-sheraton2.jpg');
INSERT INTO place_image_urls VALUES (38,'https://i.ibb.co/tDSLjSH/stay-supara1.png');
INSERT INTO place_image_urls VALUES (39,'https://i.ibb.co/HK49YbT/stay-ramada1.jpg');
INSERT INTO place_image_urls VALUES (39,'https://i.ibb.co/qC9BrYw/stay-ramada2.jpg');
INSERT INTO place_image_urls VALUES (39,'https://i.ibb.co/ZHqrjvT/stay-ramada3.jpg');
INSERT INTO place_image_urls VALUES (40,'https://i.ibb.co/k2S727R/stay-novotel1.jpg');
INSERT INTO place_image_urls VALUES (40,'https://i.ibb.co/dcrG2rb/stay-novotel2.jpg');
INSERT INTO place_image_urls VALUES (41,'https://i.ibb.co/ngWHqWC/stay-jannat1.jpg');
INSERT INTO place_image_urls VALUES (41,'https://i.ibb.co/ThYZKq4/stay-jannat2.jpg');
INSERT INTO place_image_urls VALUES (42,'https://i.ibb.co/k3KYBWd/stay-hyatt1.webp');
INSERT INTO place_image_urls VALUES (42,'https://i.ibb.co/t4mgvRk/stay-hyatt.webp');
