INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Shar', 'Naryn,Bash-Kaiyndy', 'WATERFALL','SIGHTSEEING', 'NARYN','https://asiamountains.net/adventure/horseback-riding-tours/horseback-riding-tour-from-naryn-to-tash-rabat/',
'The tallest waterfall in Central Asia “Shar” is located in the Atbash region. The place is far for 400 km from Bishkek and the length of the waterfall is also about 400m height. So, let make an amazing 4 days trip to this beautiful place and explore the real nomad’s life visiting the local family shepherd’s in the stunning mountain gorge Tuiuk Bogoshtu',41.06123258966782,76.01064524012813);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Belogorka', 'Chuy,Tash-Bulak', 'WATERFALL','SIGHTSEEING', 'CHUY','https://travelbar.kg/listings/459',
'Belogorka Gorge is situated close to the town of Sokuluk. The spot is striking for its surprising alleviation, as there are hints of a huge drop of the ground. It has the most elevated cascade in northern Kyrgyzstan, which remains at 60-meters and is known as the Belogorka Falls.The water tumbles from a tallness of 60 meters and has a fierce and full stream. The waterfall is obvious from 10-12 kilometers',42.511241879176964,74.29744019784836);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Golubinyi', 'Chuy,Chon-Kurchak', 'WATERFALL','SIGHTSEEING', 'CHUY','https://strannik.kg/excursion-to-chon-kurchak/',
'Called “Pigeon''s Waterfall” (Golubiny Vodapad in Russian). The water cascades down over sharp rocks. There is a path from the road leading to the waterfall, and sometimes people are lucky and see a flock of wild doves (pigeons) which give their name to the waterfall.',42.677350249008924,74.6014287723974);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Barskoon', 'Issyk-Kul,Barskoon', 'WATERFALL','SIGHTSEEING', 'ISSYK_KUL','https://travelbar.kg/listings/464',
'Nearby is the Barskoon Waterfall, one of the most famous waterfalls in Kyrgyzstan. Falling from a height of 24 m (79 feet), this is a spectacular waterfall, and is relatively easily accessible. There are also several other smaller waterfalls nearby.The 11th century scholar Mahmud al-Kashgari (also known as Barskhani) was a native of this area. He is best known as the author of the first comparative dictionary of the Turkic languages',42.0101134283244,77.60762439783147);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Abshir-Ata', 'Osh,Kyzyl-Kiya', 'WATERFALL','SIGHTSEEING', 'OSH','https://too.kg/abshir-ata/',
'For centuries, this waterfall was considered a sacred place, because of its unusual nature – on the territory of Kyrgyzstan there are practically no waterfalls flowing directly from the rocks. Part of this is justified by the fact that the water of the Abshir-Ata Waterfall is mineral and can really help to improve health.The waterfall is located in the beautiful valley of the river Abshir-Say at an altitude of 1500 to 2500 meters.',40.162595569402775,72.3627379977705);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Tash-Rabat', 'Naryn,At-Bashi', 'HISTORICAL_BUILDING','SIGHTSEEING', 'NARYN','https://tenti.kg/ru/tours/36/kel-suu-kl-suu',
'About 520 km from Bishkek, 125 km (1.5 hours), from Naryn, 17 km from the end of the paved road (just after the emergency airstrip) 90 km (1.5 hours) short of the border at Torugart, and at an altitude of about 3500m above sea level is the ancient caravanserai of Tash Rabat. According to one author, this is probably the best-preserved Silk Road site you will find and “no other retains as much of its original atmosphere',40.830770899846826,75.2985966455068);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'State Philharmonic', 'Chuy Avenue 253', 'HISTORICAL_BUILDING','SIGHTSEEING', 'BISHKEK','https://www.kassir.kg/hall/%D0%9A%D1%8B%D1%80%D0%B3%D1%8B%D0%B7%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BD%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%84%D0%B8%D0%BB%D0%B0%D1%80%D0%BC%D0%BE%D0%BD%D0%B8%D1%8F',
'The Kyrgyz National Philharmonic is named after Toktogul Satylganov. Satylganov was a composer and virtuoso musician. He was the most famous of the Kyrgyz Akyns – improvising poets and singers. The Kyrgyz town of Toktogul in the Jalal-Abad Region is also named in his honor.',42.87797896647584,74.5876236355818);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Burana', 'Chuy,Tokmok', 'HISTORICAL_BUILDING','SIGHTSEEING', 'CHUY','https://concept.kg/tours/inbounds/32/',
'Burana Tower, located 80 km (50 miles) from Bishkek, is one of Kyrgyzstan’s best known archaeological sites. Burana is also home to a museum of important archaeological pieces that tell the history of the Silk Road and Kyrgyzstan’s place on it.Burana Tower is all that’s left of the city of Balasagun, which was the capital of the Karakhanid Empire in the 9th century.',42.73333211661545, 75.33316130475146);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Teskey Ala-Too', 'Issyk-Kul,Karakol', 'ALPINISM','SIGHTSEEING', 'ISSYK_KUL','https://www.baibol.kg/ru/tourism-in-kyrgyzstan/attractions/%D1%82eskey-%D0%B0la-too-ridge',
'Teskey Ala-Too (Terskey Ala-Too) and Kyungyo Ala-Too are the largest mountain ranges of Kyrgyzstan, located in the northeastern part of the country. The range of Teskey Ala-Too stretches for 375 km. In the latitudinal direction from west to east, like an arc, skirting the Issyk-Kul basin from the south, then it joins the Küngöy Ala-Too ridge encircling the basin from the north.',42.00009484427672, 77.49999996572805);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Pobeda Peak', 'Issyk-Kul,Kakshaal', 'ALPINISM','SIGHTSEEING', 'ISSYK_KUL','https://www.centralasia-travel.com/ru/expeditions/pobeda',
'Peak Pobeda is regarded as the toughest 7000m Peak and of the five summits in the Snow Leopard Challenge, it lies opposite Khan Tengri on the South Inylchek Glacier. It is the most northerly 7000m peak in the world, isolated and difficult and forms the border with China. It is climbed via five or six camps and would challenge any 8000m for its harshness. The summit provides a spectacular panoramic view of the Tien Shan and Khan Tengri.',42.03627873443639, 80.12924753907441);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Lenin Peak', 'Osh,Chon-Alai', 'ALPINISM','SIGHTSEEING', 'OSH','https://www.centralasia-travel.com/ru/expeditions/lenin',
'Lenin Peak is in Osh Region, on the border with Tajikistan, and reaches a height of 7,134 m (23,406 m). In Tajikistan, the mountain is known as Ibn Sina Peak, and in Kyrgyzstan, it has been suggested to rename the peak as Manas Peak, though a mountain by that name already exists. It is the third highest peak in the CIS, and the second highest in Kyrgyzstan. It is the highest peak in the Trans-Alay Range, and the fifth highest in the Pamir Mountains.',39.344094678851256, 72.87759534405674);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Khan-Tengri', 'Issyk-Kul,Tengri-Tag', 'ALPINISM','SIGHTSEEING', 'ISSYK_KUL','https://www.centralasia-travel.com/ru/expeditions/khan-tengry',
'Khan Tengri is located to the east of Lake Issyk-Kul, near the border with Kazakhstan and China. Though the summit is only 6,995 m (22,949 feet), with the glacial cap, the summit rises to 7,010 m (22,999 feet), making this one of the five peaks in Central Asia over 7,000 (22,965 feet), and part of the Snow Leopard prize. Since the marble glows red at sunset, the mountain is known as Kantau, or Blood Mountain, in Kazakhstan',42.211116750700704, 80.17431309850288);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Alay', 'Osh,Alay', 'ALPINISM','SIGHTSEEING', 'OSH','https://www.centralasia-travel.com/ru/countries/kirgistan/sights/alay-valley',
'Alay District of Kyrgyzstan has won a place among the 2022 Green Destinations Top 100 Stories in recognition of its efforts towards responsible tourism and distinctive appeal. Alay is the first destination from Central Asia, the Commonwealth of Independent States, and the Russian-speaking countries in general to get this recognition and award.',39.66998970158205, 71.99999770932577);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Son-Kol','Naryn,Moldo-Too','LAKE','SIGHTSEEING', 'NARYN','https://travelbar.kg/listings/429',
'Song-Kol is a large alpine lake, sandwiched in a hollow between the inner spurs of the Tien Shan in the Naryn region. Sitting at 3016 meters above sea level, the lake is surrounded by virgin pastures, a conservation area, and the ridges of Sonköltoo and Moldotoo, making it the perfect site for ecological tourism.',41.83382297217287, 75.13102395694608);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Sary-Chelek','Osh,Chatkal','LAKE','SIGHTSEEING', 'OSH','https://ticket.kg/event/trehdnevniy-tur-v-sari-chelek',
' Sary Chelek is one of the most beautiful lakes in Central Asia, the lake itself and the surrounding picturesque mountains being a very popular attraction of the Chatkal Range (the western Tien Shan). The lake is situated in the western part of Kyrgyzstan, 500 km from Bishkek and 300 km from Osh, at an elevation of 1,940 m above sea level.',41.88824238248667, 71.96077580545035);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Issyk-Kol','Issyk-Kul,Tien Shan','LAKE','SIGHTSEEING', 'ISSYK_KUL','https://bestway.kg/issyk-kul',
'Issyk-Kul is a favorite holiday destination for Kyrgyzstanis. Also, the coast is visited annually by thousands of tourists from the CIS and other countries of the world. The hottest tourist season in Issyk-Kul lasts from mid-June to the end of August. In summer, the northern shore of the lake is the most attractive for tourists',42.38640906951673, 77.28596580968028);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Chatyr-Kol','Naryn,At-Bashi','LAKE','SIGHTSEEING', 'NARYN','https://triptokyrgyzstan.com/ru/destinations/places/ozero-chatyr-kul',
'Chatyr-Kul (also Chatyr-Köl) is a high-altitude lake of glacial origin, it is located at an altitude of 3,500 meters. The lake is located in the southernmost part of the Naryn Region, near the border with China, between the ranges of At-Bashi and Torugart-Too, occupying a vast territory in the intermontane depression. The lake is the third largest in Kyrgyzstan, behind Issyk-Kul and Son-Kul.',40.63878213410726, 75.31737875652597);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Skazka', 'Issyk-Kul,Tosor', 'CANYON','SIGHTSEEING', 'ISSYK_KUL','https://too.kg/skazka/',
'Skazka (Fairy Tale) Canyon, located on the southern shore of Issyk-Kul Lake, is one of the most interesting and frequently visited natural places in Kyrgyzstan. It is located 120 kilometers from Balykchi and not far from the village of Tosor.The canyon is located in the gorge of the same name and is famous for its red clay rocks.',42.15650667920104, 77.35431349783636);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Konorchek', 'Chuy,Krasnyy Most', 'CANYON','SIGHTSEEING', 'CHUY','https://asiamountains.net/adventure/tours/konorchek-canyons/',
'Konorchek Canyon is an amazing tourist destination in the eastern part of the Kyrgyz Range. It looks like a miniature Grand Canyon in the middle of the Tian-Shan Mountains! Thousands of years of soil erosion have made this place incredible.It is famous for the remains of the ancient volcano Seghizhan-Shokny. The remains of volcanoes for Kyrgyzstan are an exceptional phenomenon due to the fact that Central Asia has almost no traces of volcanoes. Even to this day, it is possible to find the remains of shells from ancient times when there was a sea.',42.59651887917175, 75.78179104017946);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Merzbacher', 'Issyk-Kul,Saryjaz', 'HIKING','SIGHTSEEING', 'ISSYK_KUL','http://www.mastertour.kg/tury-po-kyrgyzstanu/trekking/zagadochnoe-ozero-mercbakhera-9-dnejj.html',
'Merzbacher Lake is one of the strangest natural phenomena in the mountains of Kyrgyzstan, and the Enilchek Glacier one of the most spectacular and rugged landscapes. Taken together, this hike makes for one of the most memorable experiences of all the treks of Central Asia. The incredible glaciers, towering peaks, wide Enilchek valley, and uniquely beautiful Merzbacher lake make this a trek you’ll never forget. ',42.21116171382065, 79.84927649865227);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Son-Kol', 'Naryn,Moldo-Too', 'HIKING','SIGHTSEEING', 'NARYN','https://ticket.kg/event/dvuhdnevniy-tur-v-sonkol',
'Song-Kol is a large alpine lake, sandwiched in a hollow between the inner spurs of the Tien Shan in the Naryn region. Sitting at 3016 meters above sea level, the lake is surrounded by virgin pastures, a conservation area, and the ridges of Sonköltoo and Moldotoo, making it the perfect site for ecological tourism.',41.83382297217287, 75.13102395694608);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Jyrgalan', 'Issyk-Kul,Ak-Suu', 'HIKING','SIGHTSEEING', 'ISSYK_KUL','https://jyrgalan.com/tours/trekking-tours/',
'Located in far eastern Kyrgyzstan is a small, idyllic valley just opening to tourism. Arrive in the summer, and the Jyrgalan Valley greets you with lush, verdant mountains lit by bright sunshine and cooled with fresh mountain air — the perfect place for trekking adventures. As the seasons change, the valley transforms into a rich winter landscape surrounded by high mountain peaks and deep, powdery snow — optimal conditions for freeride skiing. ',42.604279072345754, 79.02737364860404);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Elcin Peak', 'Issyk-Kul,Karakol', 'HIKING','SIGHTSEEING', 'ISSYK_KUL','https://triptokyrgyzstan.com/ru/tours/voskhozhdenie-na-pik-b-elcina-5168m',
'Elcin peak (5020 m) is the most accessible highest peak to visit near Karakol. This place, which you see in the photo, can be reached in 3-4 hours of easy walking. Locals call it Oguz Bashy peak. (Bulls Head Peak) You can also spend the night in a tent at the foot of the mountain. An incredible view.',42.153182379060326, 78.43666696581057);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Ala-Kul', 'Issyk-Kul,Ak-Suu', 'HIKING','SIGHTSEEING', 'ISSYK_KUL',
'https://tour.too.kg/itinerary/%D1%82%D1%83%D1%80-%D0%BD%D0%B0-%D0%BE%D0%B7%D0%B5%D1%80%D0%BE-%D0%B0%D0%BB%D0%B0-%D0%BA%D1%83%D0%BB%D1%8C/', 'Ala Kul lake is located at an altitude of 3500 m, 20 kilometers south of the city of Karakol. The best time to visit Ala Kul lake is between early July and the end of September.  The trail to Ala Kul is well-marked, and you will find other hikers along during the hiking season, so you can hike to Ala Kul alone too.',42.317467434326545, 78.53551305055596);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Sulaiman-Too', 'Osh,Osh', 'HIKING','SIGHTSEEING', 'OSH','https://bestofosh.com/ru/tur-po-sulaiman-too/',
' Sulaiman-Too Sacred Mountain Kyrgyzstan dominates the Fergana Valley and forms the backdrop to the city of Osh, at the crossroads of important routes on the Central Asian Silk Roads. For more than one and a half millennia, Sulaiman was a beacon for travellers revered as a sacred mountain. Its five peaks and slopes contain numerous ancient places of worship and caves with petroglyphs as well as two largely reconstructed 16th century mosques',40.53028951214266, 72.78506218219451);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Kegeti', 'Chuy,Tokmok', 'GORGE','SIGHTSEEING', 'CHUY','https://www.instagram.com/kegeti_tour.kg/',
'The length of the gorge is 30 km. It is located in the northern part of Kyrgyz Ala-Too. From here to Bishkek is only 75 kilometres.A stormy mountain river carries its waters along the bottom of Kegety, into which many tributaries flow.The vegetation of these places is very diverse. Rowan, wild rose, and spruce sprouting slopes grow in abundance throughout the district.Travellers come to this area not only to relax but also to collect valuable medicinal plants and berries.',42.691097321453654, 75.1796690130174);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Karakol', 'Issyk-Kul,Karakol', 'GORGE','SIGHTSEEING', 'ISSYK_KUL','http://www.karakoltour.kg/index.php/ru/',
'Karakol gorge is located in the Terskey Ala-Too ridge which is 400 km far from Bishkek and is  close to Karakol city. The Terskey Ala-Too range is characterized by a variety of forms and relief types. The slopes of the mountains descend to Issyk-Kul Lake and end with gentle reliefs. There is an alpbase in the upper reaches of the Karakol gorge. A lot of mountains are concentrated in this zone, they direct their peaks over the snow line: Djigit (5130 m), Karakol (5281 m), Przhevalsky (4283 m), Zhukov (4450 m), Telman (4460 m), Dimitrova (4450 m), Fucik (4210 m), Gasstello (4350 m).',42.30204680393483, 78.48512555477642);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Jeti-Oguz', 'Issyk-Kul,Kyzyl-Suu', 'GORGE','SIGHTSEEING', 'ISSYK_KUL','https://sozvezdie-tour.ru/cat/tury/kirgiziya/dzhety-oguz',
'Picturesque Jeti-Oguz gorge is located 28 kilometers to the south-west of the town of Karakol. Its name is translated from Kyrgyz language means “Seven bulls”. The name is symbolic, because there is a 35 km long wall of seven huge red-brown cliffs resembling ranked furious bulls standing together.In front of the cliffs there are flat mountain slopes, thickly overgrown with grass and pine trees. Especially romantic look has the rock "Broken Heart" located at the entrance to the gorge. Jeti-Oguz is also famous for its hot springs with water enriched with radon and hydrogen sulfide. In the place they hit out of the ground, at the altitude of 2200 m, there is a resort.',42.423262433433585, 78.21063984355364);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Chunkurchak', 'Chuy,Chunkurchak', 'GORGE','SIGHTSEEING', 'CHUY','https://www.instagram.com/chunkurchak/',
'Located 25 km south of the capital, Bishkek, and nestled within spectacular colliding mountain ranges lies Chunkurchak, one of the most visually appealing destinations of Kyrgyzstan. Nestled into the beautiful countryside, complete with vast valleys, rising mountains and cascading waterfalls, Chunkurchak is a visual reminder of the stunning, natural beauty that is prevalent in this Central Asian nation',42.64217664621759, 74.6188250525896);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Altyn-Arashan', 'Issyk-Kul,Ak-Suu', 'GORGE','SIGHTSEEING', 'ISSYK_KUL','https://travelbar.kg/listings/479',
'Altyn Arashan is a gorge located in the eastern part of Kyrgyzstan, 30 kilometers away from Karakol town, located at an altitude of 2500 meters above sea level.«Altyn» means gold or golden and «Arashan» from the Sankrit means a healing hot spring. So you can say it is a golden healing hot spring. The valley is very beautiful and nature is indeed can be described as untouched. It is a wildly popular place in Kyrgyzstan both among locals and foreigners.',42.373163874656306, 78.6116182053961);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Alamedin', 'Chuy,Alamedin', 'GORGE','SIGHTSEEING', 'CHUY','https://travelbar.kg/listings/458',
'The Alamedin Gorge is one of the most famous in Kyrgyzstan. It is located near Bishkek. The river of the same name passes through Alamedin, which crosses the capital of Kyrgyzstan. The most convenient way to get into the gorge is through the village of Koi-Tash.The Alamedin Gorge is located at an altitude of 1800-2000 meters above sea level. There are waterfalls, many trees and shrubs, a birch grove, as well as stunning panoramas of mountain peaks. The most famous: Aitmatov Peak and Kyrgyzstan Peak. ',42.55192537124768, 74.66193888141089);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Fergana', 'Osh,Fergana', 'VALLEY','SIGHTSEEING', 'OSH','https://ak-sai.com/shop/express_tours/3-4-day-tours/extension-to-osh-city/',
'The Fergana Valley is an important corner of the world, located on the trade routes between empires. The Naryn and Kara Darya Rivers join in the center of the Fergana Valley to form the Syr Darya, which irrigates the valley and supports farming and agriculture. Transportation can be difficult throughout the region because of the intersecting borders and enclaves of Kyrgyzstan, Uzbekistan and Tajikistan, which sometimes bisect roads and routes.',40.39044671020174, 72.11361864735501);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Navat', 'Tokombaev Street 32/4', 'CAFE','EAT', 'BISHKEK','http://navat.kg/',
'Идеальны для проведения семейных праздников. Сохраняя и почитая многовековые традиции восточного гостеприимства, семейные ценности и почитание старших.',42.828184303354845, 74.60371110670975);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Ants Coffee', 'Erkindik Avenue 35', 'COFFEE_HOUSE','EAT', 'BISHKEK','https://www.instagram.com/ants.bishkek/',
'We are Ants''s - a city coffee house in the center of our cozy city of Bishkek! Since the opening of our doors, we have already managed to meet a lot of guests. We are sure that the atmosphere of our anthill is created not only by the interior and delicious cuisine, but also by the guests who come to us',42.87235693341139, 74.60699574069139);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'IWA Roof Bar', 'Kievskaya Street 148B', 'RESTAURANT','EAT', 'BISHKEK','https://iwa.kg/',
'IWA with 2 bars in different areas, including a dedicated smoking room. The decor has tropical elements, the tables are decorated with paintings, which, if they were paintings on their tabletops, emphasize the flavor of the establishment. "">',42.87480460463924, 74.5907715978607);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Faiza', 'Zhibek Zholu Street 555', 'CAFE','EAT', 'BISHKEK','https://faiza.kg/',
'This cafe is known among the majority of locals for its most delicious dishes. Faiza is on the market since 1992 and up until now it keeps the same taste for all the lovely meals of customers. If one wants to try local cuisine Faiza is one of the great options, the food is so nice and the place is not that expensive. ',42.88449605419548, 74.58714046895058);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Sheraton', 'Kievskaya Street 148B', 'HOTEL','STAY', 'BISHKEK','https://www.marriott.com.ru/hotels/travel/frusi-sheraton-bishkek/',
'Sheraton is one of the largest international hotel chains (tied with Hilton in first place). Founded in 1937. The owner is Marriott International. Until 2016, owned by Starwood Hotels and Resorts Worldwide.', 42.87480460463924, 74.5907715978607);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Supara', 'Chuy,Tash-Dobo', 'HOTEL','STAY', 'BISHKEK','https://supara.kg/ru/',
'Supara Chunkurchak: a successful reunification of two well-known brands.Another ambitious project of Tabyldy Egemberdiev, located just in 40 kilometers south of the capital in a beautiful place called Chunkurchak tract.This is a unique place that best addresses the meaning of the word “jailoo”, where eye catches the fantastic valley, snow-capped peaks of the majestic mountains, which are visible on the horizon. ', 42.629852934953966, 74.62202992668828);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Ramada by Wyndham', 'Isanov Street 37', 'HOTEL','STAY', 'BISHKEK','https://www.wyndhamhotels.com/ramada/bishkek-kyrgyzstan/ramada-by-wyndham-bishkek-centre/overview',
'Featuring a summer terrace and a fitness centre, Ramada by Wyndham Bishkek Center is located in the center of Bishkek.',42.871142283267446, 74.59141908066583);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Novotel', 'Manas Avenue 16', 'HOTEL','STAY', 'BISHKEK','https://all.accor.com/hotel/A145/index.ru.shtml',
'Novotel Bishkek City Center is an excellent choice for business and leisure travelers. Conveniently located in the center of Bishkek, the capital of Kyrgyzstan, our hotel offers 160 modern rooms, including the Executive Lounge on the 7th floor with panoramic views of the city and mountains. 7 fully-equipped conference rooms with natural daylight are at your disposal for successful corporate events',42.86944349530029, 74.58720182669639);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Jannat', 'Tokombaev Street 21/2', 'HOTEL','STAY', 'BISHKEK','https://jannat.kg/',
'110 rooms of nine categories are available for guests, from a standard single room to a luxurious presidential suite. A unique venue for your wedding. Incredibly beautiful summer terraces and exclusive wedding alleys.',42.8208479445571, 74.61703739069547);
INSERT INTO places (id, name, address, place_type, place_category,region, link_url, description,latitude,longitude) VALUES (nextval('places_id_seq'),'Hyatt Regency', 'Soviet Street 191', 'HOTEL','STAY', 'BISHKEK','https://www.hyatt.com/ru-RU/brands/hyatt-regency?&src=bbm_sem_bbm_search_google_eame_brand_catchall_Hyatt_Regency_hyatt%20regency&mckv=s-dc_pcrid_638809466077_mtid_5297kx13790&gclid=CjwKCAiAs8acBhA1EiwAgRFdwyvQ1VEU2GIEiRkCS5JnlOCsdtx80MzdB-sEanKUGaB4rRnp_bwZoxoCUdQQAvD_BwE&gclsrc=aw.ds',
'5 star Hotel in Bishkek. Located in the city centre, the hotel is in the heart of the business district.', 42.87956749631123, 74.6127881808501);


INSERT INTO place_image_urls VALUES (1,'https://i.ibb.co/02NPJGP/wf-shaar1.jpg');
INSERT INTO place_image_urls VALUES (1,'https://i.ibb.co/KqzcdRN/wf-shaar2.jpg');
INSERT INTO place_image_urls VALUES (2,'https://i.ibb.co/Lv9v9Cg/wf-belogorka2.jpg');
INSERT INTO place_image_urls VALUES (2,'https://i.ibb.co/ftXYcbL/wf-belogorka1.jpg');
INSERT INTO place_image_urls VALUES (3,'https://i.ibb.co/GJXr6jb/wf-golub1.jpg');
INSERT INTO place_image_urls VALUES (4,'https://i.ibb.co/LZKhK3y/wf-barskoon1.jpg');
INSERT INTO place_image_urls VALUES (4,'https://i.ibb.co/6WZb8yr/wf-barskoon2.webp');
INSERT INTO place_image_urls VALUES (5,'https://i.ibb.co/DkQ2PsS/wf-abshirata2.jpg');
INSERT INTO place_image_urls VALUES (5,'https://i.ibb.co/dGYfCws/wf-abshirata1.jpg');
INSERT INTO place_image_urls VALUES (6,'https://i.ibb.co/gJZfGbs/sight-tashrabat2.jpg');
INSERT INTO place_image_urls VALUES (7,'https://i.ibb.co/kXnjmXx/sight-filarmony2.jpg');
INSERT INTO place_image_urls VALUES (7,'https://i.ibb.co/nQqb6pW/sight-filarmony1.jpg');
INSERT INTO place_image_urls VALUES (8,'https://i.ibb.co/y8MQXLq/sight-burana1.png');
INSERT INTO place_image_urls VALUES (8,'https://i.ibb.co/FxsrKGW/sight-burana2.webp');
INSERT INTO place_image_urls VALUES (9,'https://i.ibb.co/wLKff5v/mount-teskey1.webp');
INSERT INTO place_image_urls VALUES (10,'https://i.ibb.co/1MzrqfC/mount-peak1.jpg');
INSERT INTO place_image_urls VALUES (10,'https://i.ibb.co/jzdNB9W/mount-peak2.jpg');
INSERT INTO place_image_urls VALUES (11,'https://i.ibb.co/KKy2vnD/mount-lenin1.jpg');
INSERT INTO place_image_urls VALUES (11,'https://i.ibb.co/9rhjjGQ/mount-lenin2.jpg');
INSERT INTO place_image_urls VALUES (12,'https://i.ibb.co/D9C43qm/mount-khantengri1.jpg');
INSERT INTO place_image_urls VALUES (12,'https://i.ibb.co/MBQLyH3/mount-khantengri2.png');
INSERT INTO place_image_urls VALUES (12,'https://i.ibb.co/gwy61kP/mount-khantengri3.jpg');
INSERT INTO place_image_urls VALUES (13,'https://i.ibb.co/8bWqtLJ/mount-alay1.jpg');
INSERT INTO place_image_urls VALUES (13,'https://i.ibb.co/3NJs6w9/mount-alay2.jpg');
INSERT INTO place_image_urls VALUES (14,'https://i.ibb.co/Smj618T/lake-sonkul4.jpg');
INSERT INTO place_image_urls VALUES (14,'https://i.ibb.co/qgRp4q4/lake-sonkul2.jpg');
INSERT INTO place_image_urls VALUES (15,'https://i.ibb.co/dJNZtRV/lake-sc1.jpg');
INSERT INTO place_image_urls VALUES (15,'https://i.ibb.co/KzMFNG7/lake-sc2.jpg');
INSERT INTO place_image_urls VALUES (15,'https://i.ibb.co/37PwHGH/lake-sc3.jpg');
INSERT INTO place_image_urls VALUES (16,'https://i.ibb.co/DbzNGyS/lake-ik1.jpg');
INSERT INTO place_image_urls VALUES (16,'https://i.ibb.co/k5CH2jf/lake-ik2.jpg');
INSERT INTO place_image_urls VALUES (16,'https://i.ibb.co/mSm4Z0Q/lake-ik3.jpg');
INSERT INTO place_image_urls VALUES (17,'https://i.ibb.co/mqmgL04/lake-ck1.jpg');
INSERT INTO place_image_urls VALUES (17,'https://i.ibb.co/sHfn0NC/lake-ck2.jpg');
INSERT INTO place_image_urls VALUES (17,'https://i.ibb.co/tBgm5th/lake-ck3.jpg');
INSERT INTO place_image_urls VALUES (18,'https://i.ibb.co/Ct8D8R6/kanyon-skazka1.jpg');
INSERT INTO place_image_urls VALUES (18,'https://i.ibb.co/Km7C9jZ/kanyon-skazka2.jpg');
INSERT INTO place_image_urls VALUES (19,'https://i.ibb.co/KFx5VMs/kanyon-konorchak1.jpg');
INSERT INTO place_image_urls VALUES (20,'https://i.ibb.co/gRVBwRs/hike-merzbacher1.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/6N4Zw2k/lake-sonkul3.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/D9cZGJY/lake-sonkul1.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/09nsDJf/hike-sonkul2.jpg');
INSERT INTO place_image_urls VALUES (21,'https://i.ibb.co/9w2XmvD/hike-sonkul1.jpg');
INSERT INTO place_image_urls VALUES (22,'https://i.ibb.co/6BsBBRv/hike-jyrgalan1.jpg');
INSERT INTO place_image_urls VALUES (22,'https://i.ibb.co/GTLcnSV/hike-jyrgalan2.jpg');
INSERT INTO place_image_urls VALUES (23,'https://i.ibb.co/xm97MKj/hike-elchin1.jpg');
INSERT INTO place_image_urls VALUES (23,'https://i.ibb.co/q9651mF/hike-elchin2.jpg');
INSERT INTO place_image_urls VALUES (24,'https://i.ibb.co/JyZcgtc/hike-alakul1.jpg');
INSERT INTO place_image_urls VALUES (24,'https://i.ibb.co/NWhGkgy/hike-alakul2.jpg');
INSERT INTO place_image_urls VALUES (24,'https://i.ibb.co/djy9ZbY/hike-alakul3.jpg');
INSERT INTO place_image_urls VALUES (25,'https://i.ibb.co/tMVGJYb/mount-sulainman2.jpg');
INSERT INTO place_image_urls VALUES (25,'https://i.ibb.co/9pgJWks/mount-sulainman3.png');
INSERT INTO place_image_urls VALUES (26,'https://i.ibb.co/4df5rK7/gorge-kegeti1.jpg');
INSERT INTO place_image_urls VALUES (26,'https://i.ibb.co/9TRXvT9/gorge-kegeti2.jpg');
INSERT INTO place_image_urls VALUES (27,'https://i.ibb.co/8gGZLWG/gorge-karakol1.jpg');
INSERT INTO place_image_urls VALUES (27,'https://i.ibb.co/wJhwymW/gorge-karakol2.jpg');
INSERT INTO place_image_urls VALUES (28,'https://i.ibb.co/Y3YbPZ7/gorge-jetioguz1.jpg');
INSERT INTO place_image_urls VALUES (28,'https://i.ibb.co/DRkHdxw/gorge-jetioguz2.jpg');
INSERT INTO place_image_urls VALUES (29,'https://i.ibb.co/DVkRXrN/gorge-chunkurchak1.jpg');
INSERT INTO place_image_urls VALUES (29,'https://i.ibb.co/h2Pzb1C/gorge-chunkrchak2.jpg');
INSERT INTO place_image_urls VALUES (30,'https://i.ibb.co/Kw1bdTf/gorge-altyn-arashan1.jpg');
INSERT INTO place_image_urls VALUES (30,'https://i.ibb.co/gvd1wgw/gorge-altyn-arashan2.jpg');
INSERT INTO place_image_urls VALUES (31,'https://i.ibb.co/cDtPj0X/gorge-alamedin1.png');
INSERT INTO place_image_urls VALUES (31,'https://i.ibb.co/Yddk1Dx/gorge-alamedin2.jpg');
INSERT INTO place_image_urls VALUES (32,'https://i.ibb.co/23Vqwc9/dolina-fergana1.jpg');
INSERT INTO place_image_urls VALUES (33,'https://i.ibb.co/dMZJrSP/eat-navat1.jpg');
INSERT INTO place_image_urls VALUES (33,'https://i.ibb.co/Kyqbbv4/eat-navat2.jpg');
INSERT INTO place_image_urls VALUES (34,'https://i.ibb.co/b2GprJQ/eat-ants1.jpg');
INSERT INTO place_image_urls VALUES (34,'https://i.ibb.co/74F0dWs/eat-ants2.jpg');
INSERT INTO place_image_urls VALUES (35,'https://i.ibb.co/N65Kd3b/eat-iwa1.webp');
INSERT INTO place_image_urls VALUES (35,'https://i.ibb.co/9chgXCt/eat-iwa2.jpg');
INSERT INTO place_image_urls VALUES (36,'https://i.ibb.co/vZdQkzc/eat-faiza1.jpg');
INSERT INTO place_image_urls VALUES (37,'https://i.ibb.co/dgXYcPk/stay-sheraton1.webp');
INSERT INTO place_image_urls VALUES (37,'https://i.ibb.co/PjddtG7/stay-sheraton2.jpg');
INSERT INTO place_image_urls VALUES (38,'https://i.ibb.co/tDSLjSH/stay-supara1.png');
INSERT INTO place_image_urls VALUES (39,'https://i.ibb.co/HK49YbT/stay-ramada1.jpg');
INSERT INTO place_image_urls VALUES (39,'https://i.ibb.co/qC9BrYw/stay-ramada2.jpg');
INSERT INTO place_image_urls VALUES (39,'https://i.ibb.co/ZHqrjvT/stay-ramada3.jpg');
INSERT INTO place_image_urls VALUES (40,'https://i.ibb.co/k2S727R/stay-novotel1.jpg');
INSERT INTO place_image_urls VALUES (40,'https://i.ibb.co/dcrG2rb/stay-novotel2.jpg');
INSERT INTO place_image_urls VALUES (41,'https://i.ibb.co/ngWHqWC/stay-jannat1.jpg');
INSERT INTO place_image_urls VALUES (41,'https://i.ibb.co/ThYZKq4/stay-jannat2.jpg');
INSERT INTO place_image_urls VALUES (42,'https://i.ibb.co/k3KYBWd/stay-hyatt1.webp');
INSERT INTO place_image_urls VALUES (42,'https://i.ibb.co/t4mgvRk/stay-hyatt.webp');
