INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status, creation_date)
VALUES (false, nextval('blogs_id_seq'), 5, 'My best vacation or "How I spent my holidays in Kyrgyzstan?".',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce odio est, laoreet non venenatis sit amet, feugiat in leo. Vivamus ac nibh convallis, tempor arcu ut, porta ipsum. Sed non erat mauris. Integer a faucibus tellus. Duis nec ultricies ex, eu pretium augue. Praesent in fringilla nunc, nec luctus nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam mattis bibendum varius. Fusce ante mi, auctor at rutrum nec, luctus id arcu. Nam interdum molestie orci, id commodo risus congue sit amet. Aenean a tincidunt dolor, sit amet varius lacus.

Donec scelerisque maximus est, ut suscipit lorem. Etiam interdum quis ipsum non fringilla. Donec ut tellus in sem tempus ornare et vel massa. Duis convallis efficitur congue. Aliquam id augue tellus. Phasellus arcu ex, posuere et gravida et, efficitur at nulla. Sed suscipit a metus id malesuada. Donec sollicitudin vestibulum lobortis. Sed nec magna et leo lacinia blandit. Aliquam eu elementum justo. Etiam leo odio, aliquam non augue sit amet, dapibus lobortis dui. Maecenas in aliquet arcu, vel gravida nibh. Donec consequat molestie enim vel gravida.

Integer eu purus at nisi iaculis gravida. Vestibulum ultricies justo ut augue ornare, sed fermentum mauris pharetra. Morbi semper mauris elit, in egestas tortor tristique eu. Nunc consectetur metus urna, eget varius purus auctor nec. Duis sit amet enim in lacus gravida interdum. Vivamus volutpat massa commodo, dapibus nibh quis, bibendum est. In non nulla vel metus posuere faucibus. Praesent et luctus ante.

Maecenas et nisi at ex viverra blandit. Cras eu velit dolor. Duis id sapien nec libero iaculis porta. Morbi in lorem venenatis, rutrum eros sit amet, feugiat felis. Fusce ac mollis ante. Phasellus eu nunc ornare, sollicitudin quam ac, aliquet lorem. Mauris blandit arcu eu mi lacinia, id malesuada lorem tempor. Donec efficitur cursus lectus non dapibus. Curabitur sit amet placerat est. Quisque egestas volutpat eleifend. Aliquam interdum mauris nibh, at pellentesque justo congue et. Aliquam erat volutpat. Curabitur eleifend purus purus, nec congue risus efficitur in. Quisque a congue tortor. Nulla bibendum mi non commodo finibus. Proin sem ante, sagittis sit amet erat eu, bibendum luctus urna.

Etiam bibendum justo augue, elementum vestibulum diam consectetur finibus. Curabitur ipsum dolor, dapibus quis fermentum eu, lobortis et justo. Nam at interdum arcu. Phasellus semper lorem iaculis, volutpat felis vel, tincidunt nibh. Curabitur id nisi in quam fringilla rhoncus. Nam mi urna, commodo a risus at, gravida convallis tortor. Maecenas nec nisl et mauris rhoncus ornare. Nullam volutpat tortor id laoreet tempus. Quisque tincidunt neque sed lobortis molestie. In hac habitasse platea dictumst.',
        'APPROVED', '2022-06-27');
INSERT INTO blog_image_urls VALUES (1,
    'https://i.natgeofe.com/n/91c4071e-ba4d-4f05-a002-71e63355eb13/kyrgyzstan-kol-suu_16x9.jpg');

INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status, creation_date)
VALUES (false, nextval('blogs_id_seq'), 6, 'Best lifehacks YOU NEED TO KNOW before coming to Kyrgyzstan',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce odio est, laoreet non venenatis sit amet, feugiat in leo. Vivamus ac nibh convallis, tempor arcu ut, porta ipsum. Sed non erat mauris. Integer a faucibus tellus. Duis nec ultricies ex, eu pretium augue. Praesent in fringilla nunc, nec luctus nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam mattis bibendum varius. Fusce ante mi, auctor at rutrum nec, luctus id arcu. Nam interdum molestie orci, id commodo risus congue sit amet. Aenean a tincidunt dolor, sit amet varius lacus.

Donec scelerisque maximus est, ut suscipit lorem. Etiam interdum quis ipsum non fringilla. Donec ut tellus in sem tempus ornare et vel massa. Duis convallis efficitur congue. Aliquam id augue tellus. Phasellus arcu ex, posuere et gravida et, efficitur at nulla. Sed suscipit a metus id malesuada. Donec sollicitudin vestibulum lobortis. Sed nec magna et leo lacinia blandit. Aliquam eu elementum justo. Etiam leo odio, aliquam non augue sit amet, dapibus lobortis dui. Maecenas in aliquet arcu, vel gravida nibh. Donec consequat molestie enim vel gravida.

Integer eu purus at nisi iaculis gravida. Vestibulum ultricies justo ut augue ornare, sed fermentum mauris pharetra. Morbi semper mauris elit, in egestas tortor tristique eu. Nunc consectetur metus urna, eget varius purus auctor nec. Duis sit amet enim in lacus gravida interdum. Vivamus volutpat massa commodo, dapibus nibh quis, bibendum est. In non nulla vel metus posuere faucibus. Praesent et luctus ante.

Maecenas et nisi at ex viverra blandit. Cras eu velit dolor. Duis id sapien nec libero iaculis porta. Morbi in lorem venenatis, rutrum eros sit amet, feugiat felis. Fusce ac mollis ante. Phasellus eu nunc ornare, sollicitudin quam ac, aliquet lorem. Mauris blandit arcu eu mi lacinia, id malesuada lorem tempor. Donec efficitur cursus lectus non dapibus. Curabitur sit amet placerat est. Quisque egestas volutpat eleifend. Aliquam interdum mauris nibh, at pellentesque justo congue et. Aliquam erat volutpat. Curabitur eleifend purus purus, nec congue risus efficitur in. Quisque a congue tortor. Nulla bibendum mi non commodo finibus. Proin sem ante, sagittis sit amet erat eu, bibendum luctus urna.

Etiam bibendum justo augue, elementum vestibulum diam consectetur finibus. Curabitur ipsum dolor, dapibus quis fermentum eu, lobortis et justo. Nam at interdum arcu. Phasellus semper lorem iaculis, volutpat felis vel, tincidunt nibh. Curabitur id nisi in quam fringilla rhoncus. Nam mi urna, commodo a risus at, gravida convallis tortor. Maecenas nec nisl et mauris rhoncus ornare. Nullam volutpat tortor id laoreet tempus. Quisque tincidunt neque sed lobortis molestie. In hac habitasse platea dictumst.',
        'REJECTED', '2022-07-01');
INSERT INTO blog_image_urls VALUES (2,
    'https://oir.mobi/uploads/posts/2021-05/1622302185_4-oir_mobi-p-priroda-kirgizstana-priroda-krasivo-foto-4.jpg');

INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status, creation_date)
VALUES (false, nextval('blogs_id_seq'), 7, 'My experience in Kyrgyzstan. Part - 1: People and culture',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce odio est, laoreet non venenatis sit amet, feugiat in leo. Vivamus ac nibh convallis, tempor arcu ut, porta ipsum. Sed non erat mauris. Integer a faucibus tellus. Duis nec ultricies ex, eu pretium augue. Praesent in fringilla nunc, nec luctus nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam mattis bibendum varius. Fusce ante mi, auctor at rutrum nec, luctus id arcu. Nam interdum molestie orci, id commodo risus congue sit amet. Aenean a tincidunt dolor, sit amet varius lacus.

Donec scelerisque maximus est, ut suscipit lorem. Etiam interdum quis ipsum non fringilla. Donec ut tellus in sem tempus ornare et vel massa. Duis convallis efficitur congue. Aliquam id augue tellus. Phasellus arcu ex, posuere et gravida et, efficitur at nulla. Sed suscipit a metus id malesuada. Donec sollicitudin vestibulum lobortis. Sed nec magna et leo lacinia blandit. Aliquam eu elementum justo. Etiam leo odio, aliquam non augue sit amet, dapibus lobortis dui. Maecenas in aliquet arcu, vel gravida nibh. Donec consequat molestie enim vel gravida.

Integer eu purus at nisi iaculis gravida. Vestibulum ultricies justo ut augue ornare, sed fermentum mauris pharetra. Morbi semper mauris elit, in egestas tortor tristique eu. Nunc consectetur metus urna, eget varius purus auctor nec. Duis sit amet enim in lacus gravida interdum. Vivamus volutpat massa commodo, dapibus nibh quis, bibendum est. In non nulla vel metus posuere faucibus. Praesent et luctus ante.

Maecenas et nisi at ex viverra blandit. Cras eu velit dolor. Duis id sapien nec libero iaculis porta. Morbi in lorem venenatis, rutrum eros sit amet, feugiat felis. Fusce ac mollis ante. Phasellus eu nunc ornare, sollicitudin quam ac, aliquet lorem. Mauris blandit arcu eu mi lacinia, id malesuada lorem tempor. Donec efficitur cursus lectus non dapibus. Curabitur sit amet placerat est. Quisque egestas volutpat eleifend. Aliquam interdum mauris nibh, at pellentesque justo congue et. Aliquam erat volutpat. Curabitur eleifend purus purus, nec congue risus efficitur in. Quisque a congue tortor. Nulla bibendum mi non commodo finibus. Proin sem ante, sagittis sit amet erat eu, bibendum luctus urna.

Etiam bibendum justo augue, elementum vestibulum diam consectetur finibus. Curabitur ipsum dolor, dapibus quis fermentum eu, lobortis et justo. Nam at interdum arcu. Phasellus semper lorem iaculis, volutpat felis vel, tincidunt nibh. Curabitur id nisi in quam fringilla rhoncus. Nam mi urna, commodo a risus at, gravida convallis tortor. Maecenas nec nisl et mauris rhoncus ornare. Nullam volutpat tortor id laoreet tempus. Quisque tincidunt neque sed lobortis molestie. In hac habitasse platea dictumst.',
        'PENDING', '2022-07-08');
INSERT INTO blog_image_urls VALUES (3,
    'https://marakandatravel.asia/wp-content/uploads/2019/12/68.jpg');

INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status, creation_date)
VALUES (false, nextval('blogs_id_seq'), 7, 'My experience in Kyrgyzstan. Part - 2: National foods and drinks',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce odio est, laoreet non venenatis sit amet, feugiat in leo. Vivamus ac nibh convallis, tempor arcu ut, porta ipsum. Sed non erat mauris. Integer a faucibus tellus. Duis nec ultricies ex, eu pretium augue. Praesent in fringilla nunc, nec luctus nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam mattis bibendum varius. Fusce ante mi, auctor at rutrum nec, luctus id arcu. Nam interdum molestie orci, id commodo risus congue sit amet. Aenean a tincidunt dolor, sit amet varius lacus.

Donec scelerisque maximus est, ut suscipit lorem. Etiam interdum quis ipsum non fringilla. Donec ut tellus in sem tempus ornare et vel massa. Duis convallis efficitur congue. Aliquam id augue tellus. Phasellus arcu ex, posuere et gravida et, efficitur at nulla. Sed suscipit a metus id malesuada. Donec sollicitudin vestibulum lobortis. Sed nec magna et leo lacinia blandit. Aliquam eu elementum justo. Etiam leo odio, aliquam non augue sit amet, dapibus lobortis dui. Maecenas in aliquet arcu, vel gravida nibh. Donec consequat molestie enim vel gravida.

Integer eu purus at nisi iaculis gravida. Vestibulum ultricies justo ut augue ornare, sed fermentum mauris pharetra. Morbi semper mauris elit, in egestas tortor tristique eu. Nunc consectetur metus urna, eget varius purus auctor nec. Duis sit amet enim in lacus gravida interdum. Vivamus volutpat massa commodo, dapibus nibh quis, bibendum est. In non nulla vel metus posuere faucibus. Praesent et luctus ante.

Maecenas et nisi at ex viverra blandit. Cras eu velit dolor. Duis id sapien nec libero iaculis porta. Morbi in lorem venenatis, rutrum eros sit amet, feugiat felis. Fusce ac mollis ante. Phasellus eu nunc ornare, sollicitudin quam ac, aliquet lorem. Mauris blandit arcu eu mi lacinia, id malesuada lorem tempor. Donec efficitur cursus lectus non dapibus. Curabitur sit amet placerat est. Quisque egestas volutpat eleifend. Aliquam interdum mauris nibh, at pellentesque justo congue et. Aliquam erat volutpat. Curabitur eleifend purus purus, nec congue risus efficitur in. Quisque a congue tortor. Nulla bibendum mi non commodo finibus. Proin sem ante, sagittis sit amet erat eu, bibendum luctus urna.

Etiam bibendum justo augue, elementum vestibulum diam consectetur finibus. Curabitur ipsum dolor, dapibus quis fermentum eu, lobortis et justo. Nam at interdum arcu. Phasellus semper lorem iaculis, volutpat felis vel, tincidunt nibh. Curabitur id nisi in quam fringilla rhoncus. Nam mi urna, commodo a risus at, gravida convallis tortor. Maecenas nec nisl et mauris rhoncus ornare. Nullam volutpat tortor id laoreet tempus. Quisque tincidunt neque sed lobortis molestie. In hac habitasse platea dictumst.',
        'APPROVED', '2022-07-12');
INSERT INTO blog_image_urls VALUES (4,
     'https://www.friendsofkyrgyzstan.org/assets/images/2021/03/how-to-cook-besh-barmak.jpg');

INSERT INTO blogs (is_deleted, id, author_id, title, body, review_status, creation_date)
VALUES (false, nextval('blogs_id_seq'), 7, 'My experience in Kyrgyzstan. Part - 3: Nature',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce odio est, laoreet non venenatis sit amet, feugiat in leo. Vivamus ac nibh convallis, tempor arcu ut, porta ipsum. Sed non erat mauris. Integer a faucibus tellus. Duis nec ultricies ex, eu pretium augue. Praesent in fringilla nunc, nec luctus nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam mattis bibendum varius. Fusce ante mi, auctor at rutrum nec, luctus id arcu. Nam interdum molestie orci, id commodo risus congue sit amet. Aenean a tincidunt dolor, sit amet varius lacus.

Donec scelerisque maximus est, ut suscipit lorem. Etiam interdum quis ipsum non fringilla. Donec ut tellus in sem tempus ornare et vel massa. Duis convallis efficitur congue. Aliquam id augue tellus. Phasellus arcu ex, posuere et gravida et, efficitur at nulla. Sed suscipit a metus id malesuada. Donec sollicitudin vestibulum lobortis. Sed nec magna et leo lacinia blandit. Aliquam eu elementum justo. Etiam leo odio, aliquam non augue sit amet, dapibus lobortis dui. Maecenas in aliquet arcu, vel gravida nibh. Donec consequat molestie enim vel gravida.

Integer eu purus at nisi iaculis gravida. Vestibulum ultricies justo ut augue ornare, sed fermentum mauris pharetra. Morbi semper mauris elit, in egestas tortor tristique eu. Nunc consectetur metus urna, eget varius purus auctor nec. Duis sit amet enim in lacus gravida interdum. Vivamus volutpat massa commodo, dapibus nibh quis, bibendum est. In non nulla vel metus posuere faucibus. Praesent et luctus ante.

Maecenas et nisi at ex viverra blandit. Cras eu velit dolor. Duis id sapien nec libero iaculis porta. Morbi in lorem venenatis, rutrum eros sit amet, feugiat felis. Fusce ac mollis ante. Phasellus eu nunc ornare, sollicitudin quam ac, aliquet lorem. Mauris blandit arcu eu mi lacinia, id malesuada lorem tempor. Donec efficitur cursus lectus non dapibus. Curabitur sit amet placerat est. Quisque egestas volutpat eleifend. Aliquam interdum mauris nibh, at pellentesque justo congue et. Aliquam erat volutpat. Curabitur eleifend purus purus, nec congue risus efficitur in. Quisque a congue tortor. Nulla bibendum mi non commodo finibus. Proin sem ante, sagittis sit amet erat eu, bibendum luctus urna.

Etiam bibendum justo augue, elementum vestibulum diam consectetur finibus. Curabitur ipsum dolor, dapibus quis fermentum eu, lobortis et justo. Nam at interdum arcu. Phasellus semper lorem iaculis, volutpat felis vel, tincidunt nibh. Curabitur id nisi in quam fringilla rhoncus. Nam mi urna, commodo a risus at, gravida convallis tortor. Maecenas nec nisl et mauris rhoncus ornare. Nullam volutpat tortor id laoreet tempus. Quisque tincidunt neque sed lobortis molestie. In hac habitasse platea dictumst.',
        'APPROVED', '2022-07-18');
INSERT INTO blog_image_urls VALUES (5,
    'https://oir.mobi/uploads/posts/2021-05/1622302226_50-oir_mobi-p-priroda-kirgizstana-priroda-krasivo-foto-52.jpg');